/*
Snyk API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: REST
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UpdateOrgRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateOrgRequest{}

// UpdateOrgRequest struct for UpdateOrgRequest
type UpdateOrgRequest struct {
	Data UpdateOrgRequestData `json:"data"`
}

type _UpdateOrgRequest UpdateOrgRequest

// NewUpdateOrgRequest instantiates a new UpdateOrgRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateOrgRequest(data UpdateOrgRequestData) *UpdateOrgRequest {
	this := UpdateOrgRequest{}
	this.Data = data
	return &this
}

// NewUpdateOrgRequestWithDefaults instantiates a new UpdateOrgRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateOrgRequestWithDefaults() *UpdateOrgRequest {
	this := UpdateOrgRequest{}
	return &this
}

// GetData returns the Data field value
func (o *UpdateOrgRequest) GetData() UpdateOrgRequestData {
	if o == nil {
		var ret UpdateOrgRequestData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *UpdateOrgRequest) GetDataOk() (*UpdateOrgRequestData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *UpdateOrgRequest) SetData(v UpdateOrgRequestData) {
	o.Data = v
}

func (o UpdateOrgRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateOrgRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *UpdateOrgRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateOrgRequest := _UpdateOrgRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateOrgRequest)

	if err != nil {
		return err
	}

	*o = UpdateOrgRequest(varUpdateOrgRequest)

	return err
}

type NullableUpdateOrgRequest struct {
	value *UpdateOrgRequest
	isSet bool
}

func (v NullableUpdateOrgRequest) Get() *UpdateOrgRequest {
	return v.value
}

func (v *NullableUpdateOrgRequest) Set(val *UpdateOrgRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateOrgRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateOrgRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateOrgRequest(val *UpdateOrgRequest) *NullableUpdateOrgRequest {
	return &NullableUpdateOrgRequest{value: val, isSet: true}
}

func (v NullableUpdateOrgRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateOrgRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


