/*
Snyk API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: REST
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ListOrgInvitation200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListOrgInvitation200Response{}

// ListOrgInvitation200Response struct for ListOrgInvitation200Response
type ListOrgInvitation200Response struct {
	Data []OrgInvitation `json:"data"`
	Jsonapi JsonApi `json:"jsonapi"`
	Links Links `json:"links"`
}

type _ListOrgInvitation200Response ListOrgInvitation200Response

// NewListOrgInvitation200Response instantiates a new ListOrgInvitation200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListOrgInvitation200Response(data []OrgInvitation, jsonapi JsonApi, links Links) *ListOrgInvitation200Response {
	this := ListOrgInvitation200Response{}
	this.Data = data
	this.Jsonapi = jsonapi
	this.Links = links
	return &this
}

// NewListOrgInvitation200ResponseWithDefaults instantiates a new ListOrgInvitation200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListOrgInvitation200ResponseWithDefaults() *ListOrgInvitation200Response {
	this := ListOrgInvitation200Response{}
	return &this
}

// GetData returns the Data field value
func (o *ListOrgInvitation200Response) GetData() []OrgInvitation {
	if o == nil {
		var ret []OrgInvitation
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *ListOrgInvitation200Response) GetDataOk() ([]OrgInvitation, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *ListOrgInvitation200Response) SetData(v []OrgInvitation) {
	o.Data = v
}

// GetJsonapi returns the Jsonapi field value
func (o *ListOrgInvitation200Response) GetJsonapi() JsonApi {
	if o == nil {
		var ret JsonApi
		return ret
	}

	return o.Jsonapi
}

// GetJsonapiOk returns a tuple with the Jsonapi field value
// and a boolean to check if the value has been set.
func (o *ListOrgInvitation200Response) GetJsonapiOk() (*JsonApi, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Jsonapi, true
}

// SetJsonapi sets field value
func (o *ListOrgInvitation200Response) SetJsonapi(v JsonApi) {
	o.Jsonapi = v
}

// GetLinks returns the Links field value
func (o *ListOrgInvitation200Response) GetLinks() Links {
	if o == nil {
		var ret Links
		return ret
	}

	return o.Links
}

// GetLinksOk returns a tuple with the Links field value
// and a boolean to check if the value has been set.
func (o *ListOrgInvitation200Response) GetLinksOk() (*Links, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Links, true
}

// SetLinks sets field value
func (o *ListOrgInvitation200Response) SetLinks(v Links) {
	o.Links = v
}

func (o ListOrgInvitation200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListOrgInvitation200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	toSerialize["jsonapi"] = o.Jsonapi
	toSerialize["links"] = o.Links
	return toSerialize, nil
}

func (o *ListOrgInvitation200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
		"jsonapi",
		"links",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varListOrgInvitation200Response := _ListOrgInvitation200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varListOrgInvitation200Response)

	if err != nil {
		return err
	}

	*o = ListOrgInvitation200Response(varListOrgInvitation200Response)

	return err
}

type NullableListOrgInvitation200Response struct {
	value *ListOrgInvitation200Response
	isSet bool
}

func (v NullableListOrgInvitation200Response) Get() *ListOrgInvitation200Response {
	return v.value
}

func (v *NullableListOrgInvitation200Response) Set(val *ListOrgInvitation200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableListOrgInvitation200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableListOrgInvitation200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListOrgInvitation200Response(val *ListOrgInvitation200Response) *NullableListOrgInvitation200Response {
	return &NullableListOrgInvitation200Response{value: val, isSet: true}
}

func (v NullableListOrgInvitation200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListOrgInvitation200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


