/*
Snyk API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: REST
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ListGroupAuditLogs200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListGroupAuditLogs200Response{}

// ListGroupAuditLogs200Response struct for ListGroupAuditLogs200Response
type ListGroupAuditLogs200Response struct {
	Data AuditLogSearch `json:"data"`
	Jsonapi JsonApi `json:"jsonapi"`
	Links *Links `json:"links,omitempty"`
}

type _ListGroupAuditLogs200Response ListGroupAuditLogs200Response

// NewListGroupAuditLogs200Response instantiates a new ListGroupAuditLogs200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListGroupAuditLogs200Response(data AuditLogSearch, jsonapi JsonApi) *ListGroupAuditLogs200Response {
	this := ListGroupAuditLogs200Response{}
	this.Data = data
	this.Jsonapi = jsonapi
	return &this
}

// NewListGroupAuditLogs200ResponseWithDefaults instantiates a new ListGroupAuditLogs200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListGroupAuditLogs200ResponseWithDefaults() *ListGroupAuditLogs200Response {
	this := ListGroupAuditLogs200Response{}
	return &this
}

// GetData returns the Data field value
func (o *ListGroupAuditLogs200Response) GetData() AuditLogSearch {
	if o == nil {
		var ret AuditLogSearch
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *ListGroupAuditLogs200Response) GetDataOk() (*AuditLogSearch, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *ListGroupAuditLogs200Response) SetData(v AuditLogSearch) {
	o.Data = v
}

// GetJsonapi returns the Jsonapi field value
func (o *ListGroupAuditLogs200Response) GetJsonapi() JsonApi {
	if o == nil {
		var ret JsonApi
		return ret
	}

	return o.Jsonapi
}

// GetJsonapiOk returns a tuple with the Jsonapi field value
// and a boolean to check if the value has been set.
func (o *ListGroupAuditLogs200Response) GetJsonapiOk() (*JsonApi, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Jsonapi, true
}

// SetJsonapi sets field value
func (o *ListGroupAuditLogs200Response) SetJsonapi(v JsonApi) {
	o.Jsonapi = v
}

// GetLinks returns the Links field value if set, zero value otherwise.
func (o *ListGroupAuditLogs200Response) GetLinks() Links {
	if o == nil || IsNil(o.Links) {
		var ret Links
		return ret
	}
	return *o.Links
}

// GetLinksOk returns a tuple with the Links field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListGroupAuditLogs200Response) GetLinksOk() (*Links, bool) {
	if o == nil || IsNil(o.Links) {
		return nil, false
	}
	return o.Links, true
}

// HasLinks returns a boolean if a field has been set.
func (o *ListGroupAuditLogs200Response) HasLinks() bool {
	if o != nil && !IsNil(o.Links) {
		return true
	}

	return false
}

// SetLinks gets a reference to the given Links and assigns it to the Links field.
func (o *ListGroupAuditLogs200Response) SetLinks(v Links) {
	o.Links = &v
}

func (o ListGroupAuditLogs200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListGroupAuditLogs200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	toSerialize["jsonapi"] = o.Jsonapi
	if !IsNil(o.Links) {
		toSerialize["links"] = o.Links
	}
	return toSerialize, nil
}

func (o *ListGroupAuditLogs200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
		"jsonapi",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varListGroupAuditLogs200Response := _ListGroupAuditLogs200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varListGroupAuditLogs200Response)

	if err != nil {
		return err
	}

	*o = ListGroupAuditLogs200Response(varListGroupAuditLogs200Response)

	return err
}

type NullableListGroupAuditLogs200Response struct {
	value *ListGroupAuditLogs200Response
	isSet bool
}

func (v NullableListGroupAuditLogs200Response) Get() *ListGroupAuditLogs200Response {
	return v.value
}

func (v *NullableListGroupAuditLogs200Response) Set(val *ListGroupAuditLogs200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableListGroupAuditLogs200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableListGroupAuditLogs200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListGroupAuditLogs200Response(val *ListGroupAuditLogs200Response) *NullableListGroupAuditLogs200Response {
	return &NullableListGroupAuditLogs200Response{value: val, isSet: true}
}

func (v NullableListGroupAuditLogs200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListGroupAuditLogs200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


