/*
Snyk API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: REST
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateCollection201ResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateCollection201ResponseData{}

// CreateCollection201ResponseData collection resource object
type CreateCollection201ResponseData struct {
	Attributes CollectionAttributes `json:"attributes"`
	Id string `json:"id"`
	Relationships CollectionRelationships `json:"relationships"`
	Type *string `json:"type,omitempty"`
}

type _CreateCollection201ResponseData CreateCollection201ResponseData

// NewCreateCollection201ResponseData instantiates a new CreateCollection201ResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateCollection201ResponseData(attributes CollectionAttributes, id string, relationships CollectionRelationships) *CreateCollection201ResponseData {
	this := CreateCollection201ResponseData{}
	this.Attributes = attributes
	this.Id = id
	this.Relationships = relationships
	return &this
}

// NewCreateCollection201ResponseDataWithDefaults instantiates a new CreateCollection201ResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateCollection201ResponseDataWithDefaults() *CreateCollection201ResponseData {
	this := CreateCollection201ResponseData{}
	return &this
}

// GetAttributes returns the Attributes field value
func (o *CreateCollection201ResponseData) GetAttributes() CollectionAttributes {
	if o == nil {
		var ret CollectionAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *CreateCollection201ResponseData) GetAttributesOk() (*CollectionAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *CreateCollection201ResponseData) SetAttributes(v CollectionAttributes) {
	o.Attributes = v
}

// GetId returns the Id field value
func (o *CreateCollection201ResponseData) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *CreateCollection201ResponseData) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *CreateCollection201ResponseData) SetId(v string) {
	o.Id = v
}

// GetRelationships returns the Relationships field value
func (o *CreateCollection201ResponseData) GetRelationships() CollectionRelationships {
	if o == nil {
		var ret CollectionRelationships
		return ret
	}

	return o.Relationships
}

// GetRelationshipsOk returns a tuple with the Relationships field value
// and a boolean to check if the value has been set.
func (o *CreateCollection201ResponseData) GetRelationshipsOk() (*CollectionRelationships, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Relationships, true
}

// SetRelationships sets field value
func (o *CreateCollection201ResponseData) SetRelationships(v CollectionRelationships) {
	o.Relationships = v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *CreateCollection201ResponseData) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateCollection201ResponseData) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *CreateCollection201ResponseData) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *CreateCollection201ResponseData) SetType(v string) {
	o.Type = &v
}

func (o CreateCollection201ResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateCollection201ResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["attributes"] = o.Attributes
	toSerialize["id"] = o.Id
	toSerialize["relationships"] = o.Relationships
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	return toSerialize, nil
}

func (o *CreateCollection201ResponseData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"attributes",
		"id",
		"relationships",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateCollection201ResponseData := _CreateCollection201ResponseData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateCollection201ResponseData)

	if err != nil {
		return err
	}

	*o = CreateCollection201ResponseData(varCreateCollection201ResponseData)

	return err
}

type NullableCreateCollection201ResponseData struct {
	value *CreateCollection201ResponseData
	isSet bool
}

func (v NullableCreateCollection201ResponseData) Get() *CreateCollection201ResponseData {
	return v.value
}

func (v *NullableCreateCollection201ResponseData) Set(val *CreateCollection201ResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateCollection201ResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateCollection201ResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateCollection201ResponseData(val *CreateCollection201ResponseData) *NullableCreateCollection201ResponseData {
	return &NullableCreateCollection201ResponseData{value: val, isSet: true}
}

func (v NullableCreateCollection201ResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateCollection201ResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


