/*
Snyk API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: REST
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UpdateGroupServiceAccountRequestData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateGroupServiceAccountRequestData{}

// UpdateGroupServiceAccountRequestData struct for UpdateGroupServiceAccountRequestData
type UpdateGroupServiceAccountRequestData struct {
	Attributes UpdateGroupServiceAccountRequestDataAttributes `json:"attributes"`
	// The ID of the service account. Must match the id in the url path.
	Id string `json:"id"`
	// The Resource type.
	Type string `json:"type"`
}

type _UpdateGroupServiceAccountRequestData UpdateGroupServiceAccountRequestData

// NewUpdateGroupServiceAccountRequestData instantiates a new UpdateGroupServiceAccountRequestData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateGroupServiceAccountRequestData(attributes UpdateGroupServiceAccountRequestDataAttributes, id string, type_ string) *UpdateGroupServiceAccountRequestData {
	this := UpdateGroupServiceAccountRequestData{}
	this.Attributes = attributes
	this.Id = id
	this.Type = type_
	return &this
}

// NewUpdateGroupServiceAccountRequestDataWithDefaults instantiates a new UpdateGroupServiceAccountRequestData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateGroupServiceAccountRequestDataWithDefaults() *UpdateGroupServiceAccountRequestData {
	this := UpdateGroupServiceAccountRequestData{}
	return &this
}

// GetAttributes returns the Attributes field value
func (o *UpdateGroupServiceAccountRequestData) GetAttributes() UpdateGroupServiceAccountRequestDataAttributes {
	if o == nil {
		var ret UpdateGroupServiceAccountRequestDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *UpdateGroupServiceAccountRequestData) GetAttributesOk() (*UpdateGroupServiceAccountRequestDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *UpdateGroupServiceAccountRequestData) SetAttributes(v UpdateGroupServiceAccountRequestDataAttributes) {
	o.Attributes = v
}

// GetId returns the Id field value
func (o *UpdateGroupServiceAccountRequestData) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *UpdateGroupServiceAccountRequestData) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *UpdateGroupServiceAccountRequestData) SetId(v string) {
	o.Id = v
}

// GetType returns the Type field value
func (o *UpdateGroupServiceAccountRequestData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *UpdateGroupServiceAccountRequestData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *UpdateGroupServiceAccountRequestData) SetType(v string) {
	o.Type = v
}

func (o UpdateGroupServiceAccountRequestData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateGroupServiceAccountRequestData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["attributes"] = o.Attributes
	toSerialize["id"] = o.Id
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

func (o *UpdateGroupServiceAccountRequestData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"attributes",
		"id",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateGroupServiceAccountRequestData := _UpdateGroupServiceAccountRequestData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateGroupServiceAccountRequestData)

	if err != nil {
		return err
	}

	*o = UpdateGroupServiceAccountRequestData(varUpdateGroupServiceAccountRequestData)

	return err
}

type NullableUpdateGroupServiceAccountRequestData struct {
	value *UpdateGroupServiceAccountRequestData
	isSet bool
}

func (v NullableUpdateGroupServiceAccountRequestData) Get() *UpdateGroupServiceAccountRequestData {
	return v.value
}

func (v *NullableUpdateGroupServiceAccountRequestData) Set(val *UpdateGroupServiceAccountRequestData) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateGroupServiceAccountRequestData) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateGroupServiceAccountRequestData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateGroupServiceAccountRequestData(val *UpdateGroupServiceAccountRequestData) *NullableUpdateGroupServiceAccountRequestData {
	return &NullableUpdateGroupServiceAccountRequestData{value: val, isSet: true}
}

func (v NullableUpdateGroupServiceAccountRequestData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateGroupServiceAccountRequestData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


