/*
Snyk API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: REST
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the BulkPackageUrlsRequestBodyData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BulkPackageUrlsRequestBodyData{}

// BulkPackageUrlsRequestBodyData struct for BulkPackageUrlsRequestBodyData
type BulkPackageUrlsRequestBodyData struct {
	Attributes BulkPackageUrlsRequestBodyDataAttributes `json:"attributes"`
	Type *string `json:"type,omitempty"`
}

type _BulkPackageUrlsRequestBodyData BulkPackageUrlsRequestBodyData

// NewBulkPackageUrlsRequestBodyData instantiates a new BulkPackageUrlsRequestBodyData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBulkPackageUrlsRequestBodyData(attributes BulkPackageUrlsRequestBodyDataAttributes) *BulkPackageUrlsRequestBodyData {
	this := BulkPackageUrlsRequestBodyData{}
	this.Attributes = attributes
	return &this
}

// NewBulkPackageUrlsRequestBodyDataWithDefaults instantiates a new BulkPackageUrlsRequestBodyData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBulkPackageUrlsRequestBodyDataWithDefaults() *BulkPackageUrlsRequestBodyData {
	this := BulkPackageUrlsRequestBodyData{}
	return &this
}

// GetAttributes returns the Attributes field value
func (o *BulkPackageUrlsRequestBodyData) GetAttributes() BulkPackageUrlsRequestBodyDataAttributes {
	if o == nil {
		var ret BulkPackageUrlsRequestBodyDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *BulkPackageUrlsRequestBodyData) GetAttributesOk() (*BulkPackageUrlsRequestBodyDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *BulkPackageUrlsRequestBodyData) SetAttributes(v BulkPackageUrlsRequestBodyDataAttributes) {
	o.Attributes = v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *BulkPackageUrlsRequestBodyData) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BulkPackageUrlsRequestBodyData) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *BulkPackageUrlsRequestBodyData) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *BulkPackageUrlsRequestBodyData) SetType(v string) {
	o.Type = &v
}

func (o BulkPackageUrlsRequestBodyData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BulkPackageUrlsRequestBodyData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["attributes"] = o.Attributes
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	return toSerialize, nil
}

func (o *BulkPackageUrlsRequestBodyData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBulkPackageUrlsRequestBodyData := _BulkPackageUrlsRequestBodyData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBulkPackageUrlsRequestBodyData)

	if err != nil {
		return err
	}

	*o = BulkPackageUrlsRequestBodyData(varBulkPackageUrlsRequestBodyData)

	return err
}

type NullableBulkPackageUrlsRequestBodyData struct {
	value *BulkPackageUrlsRequestBodyData
	isSet bool
}

func (v NullableBulkPackageUrlsRequestBodyData) Get() *BulkPackageUrlsRequestBodyData {
	return v.value
}

func (v *NullableBulkPackageUrlsRequestBodyData) Set(val *BulkPackageUrlsRequestBodyData) {
	v.value = val
	v.isSet = true
}

func (v NullableBulkPackageUrlsRequestBodyData) IsSet() bool {
	return v.isSet
}

func (v *NullableBulkPackageUrlsRequestBodyData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBulkPackageUrlsRequestBodyData(val *BulkPackageUrlsRequestBodyData) *NullableBulkPackageUrlsRequestBodyData {
	return &NullableBulkPackageUrlsRequestBodyData{value: val, isSet: true}
}

func (v NullableBulkPackageUrlsRequestBodyData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBulkPackageUrlsRequestBodyData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


