/*
Snyk API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: REST
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GetAppInstallsForGroup400Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetAppInstallsForGroup400Response{}

// GetAppInstallsForGroup400Response struct for GetAppInstallsForGroup400Response
type GetAppInstallsForGroup400Response struct {
	Errors []GetAppInstallsForGroup400ResponseErrorsInner `json:"errors"`
	Jsonapi GetAppInstallsForGroup400ResponseJsonapi `json:"jsonapi"`
}

type _GetAppInstallsForGroup400Response GetAppInstallsForGroup400Response

// NewGetAppInstallsForGroup400Response instantiates a new GetAppInstallsForGroup400Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetAppInstallsForGroup400Response(errors []GetAppInstallsForGroup400ResponseErrorsInner, jsonapi GetAppInstallsForGroup400ResponseJsonapi) *GetAppInstallsForGroup400Response {
	this := GetAppInstallsForGroup400Response{}
	this.Errors = errors
	this.Jsonapi = jsonapi
	return &this
}

// NewGetAppInstallsForGroup400ResponseWithDefaults instantiates a new GetAppInstallsForGroup400Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetAppInstallsForGroup400ResponseWithDefaults() *GetAppInstallsForGroup400Response {
	this := GetAppInstallsForGroup400Response{}
	return &this
}

// GetErrors returns the Errors field value
func (o *GetAppInstallsForGroup400Response) GetErrors() []GetAppInstallsForGroup400ResponseErrorsInner {
	if o == nil {
		var ret []GetAppInstallsForGroup400ResponseErrorsInner
		return ret
	}

	return o.Errors
}

// GetErrorsOk returns a tuple with the Errors field value
// and a boolean to check if the value has been set.
func (o *GetAppInstallsForGroup400Response) GetErrorsOk() ([]GetAppInstallsForGroup400ResponseErrorsInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Errors, true
}

// SetErrors sets field value
func (o *GetAppInstallsForGroup400Response) SetErrors(v []GetAppInstallsForGroup400ResponseErrorsInner) {
	o.Errors = v
}

// GetJsonapi returns the Jsonapi field value
func (o *GetAppInstallsForGroup400Response) GetJsonapi() GetAppInstallsForGroup400ResponseJsonapi {
	if o == nil {
		var ret GetAppInstallsForGroup400ResponseJsonapi
		return ret
	}

	return o.Jsonapi
}

// GetJsonapiOk returns a tuple with the Jsonapi field value
// and a boolean to check if the value has been set.
func (o *GetAppInstallsForGroup400Response) GetJsonapiOk() (*GetAppInstallsForGroup400ResponseJsonapi, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Jsonapi, true
}

// SetJsonapi sets field value
func (o *GetAppInstallsForGroup400Response) SetJsonapi(v GetAppInstallsForGroup400ResponseJsonapi) {
	o.Jsonapi = v
}

func (o GetAppInstallsForGroup400Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetAppInstallsForGroup400Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["errors"] = o.Errors
	toSerialize["jsonapi"] = o.Jsonapi
	return toSerialize, nil
}

func (o *GetAppInstallsForGroup400Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"errors",
		"jsonapi",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetAppInstallsForGroup400Response := _GetAppInstallsForGroup400Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetAppInstallsForGroup400Response)

	if err != nil {
		return err
	}

	*o = GetAppInstallsForGroup400Response(varGetAppInstallsForGroup400Response)

	return err
}

type NullableGetAppInstallsForGroup400Response struct {
	value *GetAppInstallsForGroup400Response
	isSet bool
}

func (v NullableGetAppInstallsForGroup400Response) Get() *GetAppInstallsForGroup400Response {
	return v.value
}

func (v *NullableGetAppInstallsForGroup400Response) Set(val *GetAppInstallsForGroup400Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetAppInstallsForGroup400Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetAppInstallsForGroup400Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetAppInstallsForGroup400Response(val *GetAppInstallsForGroup400Response) *NullableGetAppInstallsForGroup400Response {
	return &NullableGetAppInstallsForGroup400Response{value: val, isSet: true}
}

func (v NullableGetAppInstallsForGroup400Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetAppInstallsForGroup400Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


