/*
Snyk API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: REST
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GetApps200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetApps200Response{}

// GetApps200Response struct for GetApps200Response
type GetApps200Response struct {
	Data []AppData `json:"data"`
	Jsonapi JsonApi `json:"jsonapi"`
	Links PaginatedLinks `json:"links"`
}

type _GetApps200Response GetApps200Response

// NewGetApps200Response instantiates a new GetApps200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetApps200Response(data []AppData, jsonapi JsonApi, links PaginatedLinks) *GetApps200Response {
	this := GetApps200Response{}
	this.Data = data
	this.Jsonapi = jsonapi
	this.Links = links
	return &this
}

// NewGetApps200ResponseWithDefaults instantiates a new GetApps200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetApps200ResponseWithDefaults() *GetApps200Response {
	this := GetApps200Response{}
	return &this
}

// GetData returns the Data field value
func (o *GetApps200Response) GetData() []AppData {
	if o == nil {
		var ret []AppData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *GetApps200Response) GetDataOk() ([]AppData, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *GetApps200Response) SetData(v []AppData) {
	o.Data = v
}

// GetJsonapi returns the Jsonapi field value
func (o *GetApps200Response) GetJsonapi() JsonApi {
	if o == nil {
		var ret JsonApi
		return ret
	}

	return o.Jsonapi
}

// GetJsonapiOk returns a tuple with the Jsonapi field value
// and a boolean to check if the value has been set.
func (o *GetApps200Response) GetJsonapiOk() (*JsonApi, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Jsonapi, true
}

// SetJsonapi sets field value
func (o *GetApps200Response) SetJsonapi(v JsonApi) {
	o.Jsonapi = v
}

// GetLinks returns the Links field value
func (o *GetApps200Response) GetLinks() PaginatedLinks {
	if o == nil {
		var ret PaginatedLinks
		return ret
	}

	return o.Links
}

// GetLinksOk returns a tuple with the Links field value
// and a boolean to check if the value has been set.
func (o *GetApps200Response) GetLinksOk() (*PaginatedLinks, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Links, true
}

// SetLinks sets field value
func (o *GetApps200Response) SetLinks(v PaginatedLinks) {
	o.Links = v
}

func (o GetApps200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetApps200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	toSerialize["jsonapi"] = o.Jsonapi
	toSerialize["links"] = o.Links
	return toSerialize, nil
}

func (o *GetApps200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
		"jsonapi",
		"links",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetApps200Response := _GetApps200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetApps200Response)

	if err != nil {
		return err
	}

	*o = GetApps200Response(varGetApps200Response)

	return err
}

type NullableGetApps200Response struct {
	value *GetApps200Response
	isSet bool
}

func (v NullableGetApps200Response) Get() *GetApps200Response {
	return v.value
}

func (v *NullableGetApps200Response) Set(val *GetApps200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetApps200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetApps200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetApps200Response(val *GetApps200Response) *NullableGetApps200Response {
	return &NullableGetApps200Response{value: val, isSet: true}
}

func (v NullableGetApps200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetApps200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


