/*
Snyk API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: REST
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the JsonApi type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &JsonApi{}

// JsonApi struct for JsonApi
type JsonApi struct {
	// Version of the JSON API specification this server supports.
	Version string `json:"version"`
}

type _JsonApi JsonApi

// NewJsonApi instantiates a new JsonApi object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewJsonApi(version string) *JsonApi {
	this := JsonApi{}
	this.Version = version
	return &this
}

// NewJsonApiWithDefaults instantiates a new JsonApi object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewJsonApiWithDefaults() *JsonApi {
	this := JsonApi{}
	return &this
}

// GetVersion returns the Version field value
func (o *JsonApi) GetVersion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Version
}

// GetVersionOk returns a tuple with the Version field value
// and a boolean to check if the value has been set.
func (o *JsonApi) GetVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Version, true
}

// SetVersion sets field value
func (o *JsonApi) SetVersion(v string) {
	o.Version = v
}

func (o JsonApi) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o JsonApi) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["version"] = o.Version
	return toSerialize, nil
}

func (o *JsonApi) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"version",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varJsonApi := _JsonApi{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varJsonApi)

	if err != nil {
		return err
	}

	*o = JsonApi(varJsonApi)

	return err
}

type NullableJsonApi struct {
	value *JsonApi
	isSet bool
}

func (v NullableJsonApi) Get() *JsonApi {
	return v.value
}

func (v *NullableJsonApi) Set(val *JsonApi) {
	v.value = val
	v.isSet = true
}

func (v NullableJsonApi) IsSet() bool {
	return v.isSet
}

func (v *NullableJsonApi) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableJsonApi(val *JsonApi) *NullableJsonApi {
	return &NullableJsonApi{value: val, isSet: true}
}

func (v NullableJsonApi) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableJsonApi) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


