/*
Snyk API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: REST
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the MemberRoleRelationshipData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MemberRoleRelationshipData{}

// MemberRoleRelationshipData struct for MemberRoleRelationshipData
type MemberRoleRelationshipData struct {
	Attributes *OrgRoleAttributes `json:"attributes,omitempty"`
	// The Snyk ID of the organization role.
	Id string `json:"id"`
	Type string `json:"type"`
}

type _MemberRoleRelationshipData MemberRoleRelationshipData

// NewMemberRoleRelationshipData instantiates a new MemberRoleRelationshipData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMemberRoleRelationshipData(id string, type_ string) *MemberRoleRelationshipData {
	this := MemberRoleRelationshipData{}
	this.Id = id
	this.Type = type_
	return &this
}

// NewMemberRoleRelationshipDataWithDefaults instantiates a new MemberRoleRelationshipData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMemberRoleRelationshipDataWithDefaults() *MemberRoleRelationshipData {
	this := MemberRoleRelationshipData{}
	return &this
}

// GetAttributes returns the Attributes field value if set, zero value otherwise.
func (o *MemberRoleRelationshipData) GetAttributes() OrgRoleAttributes {
	if o == nil || IsNil(o.Attributes) {
		var ret OrgRoleAttributes
		return ret
	}
	return *o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MemberRoleRelationshipData) GetAttributesOk() (*OrgRoleAttributes, bool) {
	if o == nil || IsNil(o.Attributes) {
		return nil, false
	}
	return o.Attributes, true
}

// HasAttributes returns a boolean if a field has been set.
func (o *MemberRoleRelationshipData) HasAttributes() bool {
	if o != nil && !IsNil(o.Attributes) {
		return true
	}

	return false
}

// SetAttributes gets a reference to the given OrgRoleAttributes and assigns it to the Attributes field.
func (o *MemberRoleRelationshipData) SetAttributes(v OrgRoleAttributes) {
	o.Attributes = &v
}

// GetId returns the Id field value
func (o *MemberRoleRelationshipData) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *MemberRoleRelationshipData) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *MemberRoleRelationshipData) SetId(v string) {
	o.Id = v
}

// GetType returns the Type field value
func (o *MemberRoleRelationshipData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *MemberRoleRelationshipData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *MemberRoleRelationshipData) SetType(v string) {
	o.Type = v
}

func (o MemberRoleRelationshipData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MemberRoleRelationshipData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Attributes) {
		toSerialize["attributes"] = o.Attributes
	}
	toSerialize["id"] = o.Id
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

func (o *MemberRoleRelationshipData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMemberRoleRelationshipData := _MemberRoleRelationshipData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMemberRoleRelationshipData)

	if err != nil {
		return err
	}

	*o = MemberRoleRelationshipData(varMemberRoleRelationshipData)

	return err
}

type NullableMemberRoleRelationshipData struct {
	value *MemberRoleRelationshipData
	isSet bool
}

func (v NullableMemberRoleRelationshipData) Get() *MemberRoleRelationshipData {
	return v.value
}

func (v *NullableMemberRoleRelationshipData) Set(val *MemberRoleRelationshipData) {
	v.value = val
	v.isSet = true
}

func (v NullableMemberRoleRelationshipData) IsSet() bool {
	return v.isSet
}

func (v *NullableMemberRoleRelationshipData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMemberRoleRelationshipData(val *MemberRoleRelationshipData) *NullableMemberRoleRelationshipData {
	return &NullableMemberRoleRelationshipData{value: val, isSet: true}
}

func (v NullableMemberRoleRelationshipData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMemberRoleRelationshipData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


