/*
Snyk API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: REST
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
)

// checks if the UpdateOrgProject200ResponseDataMeta type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateOrgProject200ResponseDataMeta{}

// UpdateOrgProject200ResponseDataMeta struct for UpdateOrgProject200ResponseDataMeta
type UpdateOrgProject200ResponseDataMeta struct {
	// The date that the project was last uploaded and monitored using cli.
	CliMonitoredAt NullableTime `json:"cli_monitored_at,omitempty"`
}

// NewUpdateOrgProject200ResponseDataMeta instantiates a new UpdateOrgProject200ResponseDataMeta object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateOrgProject200ResponseDataMeta() *UpdateOrgProject200ResponseDataMeta {
	this := UpdateOrgProject200ResponseDataMeta{}
	return &this
}

// NewUpdateOrgProject200ResponseDataMetaWithDefaults instantiates a new UpdateOrgProject200ResponseDataMeta object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateOrgProject200ResponseDataMetaWithDefaults() *UpdateOrgProject200ResponseDataMeta {
	this := UpdateOrgProject200ResponseDataMeta{}
	return &this
}

// GetCliMonitoredAt returns the CliMonitoredAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateOrgProject200ResponseDataMeta) GetCliMonitoredAt() time.Time {
	if o == nil || IsNil(o.CliMonitoredAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.CliMonitoredAt.Get()
}

// GetCliMonitoredAtOk returns a tuple with the CliMonitoredAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateOrgProject200ResponseDataMeta) GetCliMonitoredAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.CliMonitoredAt.Get(), o.CliMonitoredAt.IsSet()
}

// HasCliMonitoredAt returns a boolean if a field has been set.
func (o *UpdateOrgProject200ResponseDataMeta) HasCliMonitoredAt() bool {
	if o != nil && o.CliMonitoredAt.IsSet() {
		return true
	}

	return false
}

// SetCliMonitoredAt gets a reference to the given NullableTime and assigns it to the CliMonitoredAt field.
func (o *UpdateOrgProject200ResponseDataMeta) SetCliMonitoredAt(v time.Time) {
	o.CliMonitoredAt.Set(&v)
}
// SetCliMonitoredAtNil sets the value for CliMonitoredAt to be an explicit nil
func (o *UpdateOrgProject200ResponseDataMeta) SetCliMonitoredAtNil() {
	o.CliMonitoredAt.Set(nil)
}

// UnsetCliMonitoredAt ensures that no value is present for CliMonitoredAt, not even an explicit nil
func (o *UpdateOrgProject200ResponseDataMeta) UnsetCliMonitoredAt() {
	o.CliMonitoredAt.Unset()
}

func (o UpdateOrgProject200ResponseDataMeta) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateOrgProject200ResponseDataMeta) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.CliMonitoredAt.IsSet() {
		toSerialize["cli_monitored_at"] = o.CliMonitoredAt.Get()
	}
	return toSerialize, nil
}

type NullableUpdateOrgProject200ResponseDataMeta struct {
	value *UpdateOrgProject200ResponseDataMeta
	isSet bool
}

func (v NullableUpdateOrgProject200ResponseDataMeta) Get() *UpdateOrgProject200ResponseDataMeta {
	return v.value
}

func (v *NullableUpdateOrgProject200ResponseDataMeta) Set(val *UpdateOrgProject200ResponseDataMeta) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateOrgProject200ResponseDataMeta) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateOrgProject200ResponseDataMeta) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateOrgProject200ResponseDataMeta(val *UpdateOrgProject200ResponseDataMeta) *NullableUpdateOrgProject200ResponseDataMeta {
	return &NullableUpdateOrgProject200ResponseDataMeta{value: val, isSet: true}
}

func (v NullableUpdateOrgProject200ResponseDataMeta) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateOrgProject200ResponseDataMeta) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


