/*
Snyk API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: REST
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GroupIacSettingsResponseAttributesCustomRules type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GroupIacSettingsResponseAttributesCustomRules{}

// GroupIacSettingsResponseAttributesCustomRules The Infrastructure as Code custom rules settings for a group.
type GroupIacSettingsResponseAttributesCustomRules struct {
	// Whether the custom rules feature is enabled or not.
	IsEnabled *bool `json:"is_enabled,omitempty"`
	// The tag for an OCI artifact inside an OCI registry.
	OciRegistryTag *string `json:"oci_registry_tag,omitempty"`
	// The URL to an OCI registry.
	OciRegistryUrl *string `json:"oci_registry_url,omitempty"`
}

// NewGroupIacSettingsResponseAttributesCustomRules instantiates a new GroupIacSettingsResponseAttributesCustomRules object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGroupIacSettingsResponseAttributesCustomRules() *GroupIacSettingsResponseAttributesCustomRules {
	this := GroupIacSettingsResponseAttributesCustomRules{}
	return &this
}

// NewGroupIacSettingsResponseAttributesCustomRulesWithDefaults instantiates a new GroupIacSettingsResponseAttributesCustomRules object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGroupIacSettingsResponseAttributesCustomRulesWithDefaults() *GroupIacSettingsResponseAttributesCustomRules {
	this := GroupIacSettingsResponseAttributesCustomRules{}
	return &this
}

// GetIsEnabled returns the IsEnabled field value if set, zero value otherwise.
func (o *GroupIacSettingsResponseAttributesCustomRules) GetIsEnabled() bool {
	if o == nil || IsNil(o.IsEnabled) {
		var ret bool
		return ret
	}
	return *o.IsEnabled
}

// GetIsEnabledOk returns a tuple with the IsEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GroupIacSettingsResponseAttributesCustomRules) GetIsEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.IsEnabled) {
		return nil, false
	}
	return o.IsEnabled, true
}

// HasIsEnabled returns a boolean if a field has been set.
func (o *GroupIacSettingsResponseAttributesCustomRules) HasIsEnabled() bool {
	if o != nil && !IsNil(o.IsEnabled) {
		return true
	}

	return false
}

// SetIsEnabled gets a reference to the given bool and assigns it to the IsEnabled field.
func (o *GroupIacSettingsResponseAttributesCustomRules) SetIsEnabled(v bool) {
	o.IsEnabled = &v
}

// GetOciRegistryTag returns the OciRegistryTag field value if set, zero value otherwise.
func (o *GroupIacSettingsResponseAttributesCustomRules) GetOciRegistryTag() string {
	if o == nil || IsNil(o.OciRegistryTag) {
		var ret string
		return ret
	}
	return *o.OciRegistryTag
}

// GetOciRegistryTagOk returns a tuple with the OciRegistryTag field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GroupIacSettingsResponseAttributesCustomRules) GetOciRegistryTagOk() (*string, bool) {
	if o == nil || IsNil(o.OciRegistryTag) {
		return nil, false
	}
	return o.OciRegistryTag, true
}

// HasOciRegistryTag returns a boolean if a field has been set.
func (o *GroupIacSettingsResponseAttributesCustomRules) HasOciRegistryTag() bool {
	if o != nil && !IsNil(o.OciRegistryTag) {
		return true
	}

	return false
}

// SetOciRegistryTag gets a reference to the given string and assigns it to the OciRegistryTag field.
func (o *GroupIacSettingsResponseAttributesCustomRules) SetOciRegistryTag(v string) {
	o.OciRegistryTag = &v
}

// GetOciRegistryUrl returns the OciRegistryUrl field value if set, zero value otherwise.
func (o *GroupIacSettingsResponseAttributesCustomRules) GetOciRegistryUrl() string {
	if o == nil || IsNil(o.OciRegistryUrl) {
		var ret string
		return ret
	}
	return *o.OciRegistryUrl
}

// GetOciRegistryUrlOk returns a tuple with the OciRegistryUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GroupIacSettingsResponseAttributesCustomRules) GetOciRegistryUrlOk() (*string, bool) {
	if o == nil || IsNil(o.OciRegistryUrl) {
		return nil, false
	}
	return o.OciRegistryUrl, true
}

// HasOciRegistryUrl returns a boolean if a field has been set.
func (o *GroupIacSettingsResponseAttributesCustomRules) HasOciRegistryUrl() bool {
	if o != nil && !IsNil(o.OciRegistryUrl) {
		return true
	}

	return false
}

// SetOciRegistryUrl gets a reference to the given string and assigns it to the OciRegistryUrl field.
func (o *GroupIacSettingsResponseAttributesCustomRules) SetOciRegistryUrl(v string) {
	o.OciRegistryUrl = &v
}

func (o GroupIacSettingsResponseAttributesCustomRules) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GroupIacSettingsResponseAttributesCustomRules) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.IsEnabled) {
		toSerialize["is_enabled"] = o.IsEnabled
	}
	if !IsNil(o.OciRegistryTag) {
		toSerialize["oci_registry_tag"] = o.OciRegistryTag
	}
	if !IsNil(o.OciRegistryUrl) {
		toSerialize["oci_registry_url"] = o.OciRegistryUrl
	}
	return toSerialize, nil
}

type NullableGroupIacSettingsResponseAttributesCustomRules struct {
	value *GroupIacSettingsResponseAttributesCustomRules
	isSet bool
}

func (v NullableGroupIacSettingsResponseAttributesCustomRules) Get() *GroupIacSettingsResponseAttributesCustomRules {
	return v.value
}

func (v *NullableGroupIacSettingsResponseAttributesCustomRules) Set(val *GroupIacSettingsResponseAttributesCustomRules) {
	v.value = val
	v.isSet = true
}

func (v NullableGroupIacSettingsResponseAttributesCustomRules) IsSet() bool {
	return v.isSet
}

func (v *NullableGroupIacSettingsResponseAttributesCustomRules) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGroupIacSettingsResponseAttributesCustomRules(val *GroupIacSettingsResponseAttributesCustomRules) *NullableGroupIacSettingsResponseAttributesCustomRules {
	return &NullableGroupIacSettingsResponseAttributesCustomRules{value: val, isSet: true}
}

func (v NullableGroupIacSettingsResponseAttributesCustomRules) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGroupIacSettingsResponseAttributesCustomRules) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


