/*
Snyk API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: REST
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SbomResource type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SbomResource{}

// SbomResource struct for SbomResource
type SbomResource struct {
	Id string `json:"id"`
	Type string `json:"type"`
}

type _SbomResource SbomResource

// NewSbomResource instantiates a new SbomResource object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSbomResource(id string, type_ string) *SbomResource {
	this := SbomResource{}
	this.Id = id
	this.Type = type_
	return &this
}

// NewSbomResourceWithDefaults instantiates a new SbomResource object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSbomResourceWithDefaults() *SbomResource {
	this := SbomResource{}
	return &this
}

// GetId returns the Id field value
func (o *SbomResource) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *SbomResource) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *SbomResource) SetId(v string) {
	o.Id = v
}

// GetType returns the Type field value
func (o *SbomResource) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *SbomResource) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *SbomResource) SetType(v string) {
	o.Type = v
}

func (o SbomResource) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SbomResource) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

func (o *SbomResource) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSbomResource := _SbomResource{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSbomResource)

	if err != nil {
		return err
	}

	*o = SbomResource(varSbomResource)

	return err
}

type NullableSbomResource struct {
	value *SbomResource
	isSet bool
}

func (v NullableSbomResource) Get() *SbomResource {
	return v.value
}

func (v *NullableSbomResource) Set(val *SbomResource) {
	v.value = val
	v.isSet = true
}

func (v NullableSbomResource) IsSet() bool {
	return v.isSet
}

func (v *NullableSbomResource) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSbomResource(val *SbomResource) *NullableSbomResource {
	return &NullableSbomResource{value: val, isSet: true}
}

func (v NullableSbomResource) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSbomResource) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


