/*
Snyk API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: REST
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the OrgIacSettingsRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OrgIacSettingsRequest{}

// OrgIacSettingsRequest The Infrastructure as Code settings for an org.
type OrgIacSettingsRequest struct {
	Attributes OrgIacSettingsRequestAttributes `json:"attributes"`
	// Content type
	Type string `json:"type"`
}

type _OrgIacSettingsRequest OrgIacSettingsRequest

// NewOrgIacSettingsRequest instantiates a new OrgIacSettingsRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrgIacSettingsRequest(attributes OrgIacSettingsRequestAttributes, type_ string) *OrgIacSettingsRequest {
	this := OrgIacSettingsRequest{}
	this.Attributes = attributes
	this.Type = type_
	return &this
}

// NewOrgIacSettingsRequestWithDefaults instantiates a new OrgIacSettingsRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrgIacSettingsRequestWithDefaults() *OrgIacSettingsRequest {
	this := OrgIacSettingsRequest{}
	return &this
}

// GetAttributes returns the Attributes field value
func (o *OrgIacSettingsRequest) GetAttributes() OrgIacSettingsRequestAttributes {
	if o == nil {
		var ret OrgIacSettingsRequestAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *OrgIacSettingsRequest) GetAttributesOk() (*OrgIacSettingsRequestAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *OrgIacSettingsRequest) SetAttributes(v OrgIacSettingsRequestAttributes) {
	o.Attributes = v
}

// GetType returns the Type field value
func (o *OrgIacSettingsRequest) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *OrgIacSettingsRequest) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *OrgIacSettingsRequest) SetType(v string) {
	o.Type = v
}

func (o OrgIacSettingsRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OrgIacSettingsRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["attributes"] = o.Attributes
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

func (o *OrgIacSettingsRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"attributes",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOrgIacSettingsRequest := _OrgIacSettingsRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOrgIacSettingsRequest)

	if err != nil {
		return err
	}

	*o = OrgIacSettingsRequest(varOrgIacSettingsRequest)

	return err
}

type NullableOrgIacSettingsRequest struct {
	value *OrgIacSettingsRequest
	isSet bool
}

func (v NullableOrgIacSettingsRequest) Get() *OrgIacSettingsRequest {
	return v.value
}

func (v *NullableOrgIacSettingsRequest) Set(val *OrgIacSettingsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableOrgIacSettingsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableOrgIacSettingsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrgIacSettingsRequest(val *OrgIacSettingsRequest) *NullableOrgIacSettingsRequest {
	return &NullableOrgIacSettingsRequest{value: val, isSet: true}
}

func (v NullableOrgIacSettingsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrgIacSettingsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


