/*
Snyk API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: REST
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SettingsRequestData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SettingsRequestData{}

// SettingsRequestData struct for SettingsRequestData
type SettingsRequestData struct {
	Attributes SettingsAttributes `json:"attributes"`
	Type string `json:"type"`
}

type _SettingsRequestData SettingsRequestData

// NewSettingsRequestData instantiates a new SettingsRequestData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSettingsRequestData(attributes SettingsAttributes, type_ string) *SettingsRequestData {
	this := SettingsRequestData{}
	this.Attributes = attributes
	this.Type = type_
	return &this
}

// NewSettingsRequestDataWithDefaults instantiates a new SettingsRequestData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSettingsRequestDataWithDefaults() *SettingsRequestData {
	this := SettingsRequestData{}
	return &this
}

// GetAttributes returns the Attributes field value
func (o *SettingsRequestData) GetAttributes() SettingsAttributes {
	if o == nil {
		var ret SettingsAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *SettingsRequestData) GetAttributesOk() (*SettingsAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *SettingsRequestData) SetAttributes(v SettingsAttributes) {
	o.Attributes = v
}

// GetType returns the Type field value
func (o *SettingsRequestData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *SettingsRequestData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *SettingsRequestData) SetType(v string) {
	o.Type = v
}

func (o SettingsRequestData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SettingsRequestData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["attributes"] = o.Attributes
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

func (o *SettingsRequestData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"attributes",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSettingsRequestData := _SettingsRequestData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSettingsRequestData)

	if err != nil {
		return err
	}

	*o = SettingsRequestData(varSettingsRequestData)

	return err
}

type NullableSettingsRequestData struct {
	value *SettingsRequestData
	isSet bool
}

func (v NullableSettingsRequestData) Get() *SettingsRequestData {
	return v.value
}

func (v *NullableSettingsRequestData) Set(val *SettingsRequestData) {
	v.value = val
	v.isSet = true
}

func (v NullableSettingsRequestData) IsSet() bool {
	return v.isSet
}

func (v *NullableSettingsRequestData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSettingsRequestData(val *SettingsRequestData) *NullableSettingsRequestData {
	return &NullableSettingsRequestData{value: val, isSet: true}
}

func (v NullableSettingsRequestData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSettingsRequestData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


