/*
Snyk API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: REST
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AppDataWithSecret type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AppDataWithSecret{}

// AppDataWithSecret struct for AppDataWithSecret
type AppDataWithSecret struct {
	Attributes AppResourceAttributesWithSecret `json:"attributes"`
	Id string `json:"id"`
	Type string `json:"type"`
}

type _AppDataWithSecret AppDataWithSecret

// NewAppDataWithSecret instantiates a new AppDataWithSecret object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAppDataWithSecret(attributes AppResourceAttributesWithSecret, id string, type_ string) *AppDataWithSecret {
	this := AppDataWithSecret{}
	this.Attributes = attributes
	this.Id = id
	this.Type = type_
	return &this
}

// NewAppDataWithSecretWithDefaults instantiates a new AppDataWithSecret object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAppDataWithSecretWithDefaults() *AppDataWithSecret {
	this := AppDataWithSecret{}
	return &this
}

// GetAttributes returns the Attributes field value
func (o *AppDataWithSecret) GetAttributes() AppResourceAttributesWithSecret {
	if o == nil {
		var ret AppResourceAttributesWithSecret
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *AppDataWithSecret) GetAttributesOk() (*AppResourceAttributesWithSecret, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *AppDataWithSecret) SetAttributes(v AppResourceAttributesWithSecret) {
	o.Attributes = v
}

// GetId returns the Id field value
func (o *AppDataWithSecret) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *AppDataWithSecret) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *AppDataWithSecret) SetId(v string) {
	o.Id = v
}

// GetType returns the Type field value
func (o *AppDataWithSecret) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *AppDataWithSecret) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *AppDataWithSecret) SetType(v string) {
	o.Type = v
}

func (o AppDataWithSecret) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AppDataWithSecret) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["attributes"] = o.Attributes
	toSerialize["id"] = o.Id
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

func (o *AppDataWithSecret) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"attributes",
		"id",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAppDataWithSecret := _AppDataWithSecret{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAppDataWithSecret)

	if err != nil {
		return err
	}

	*o = AppDataWithSecret(varAppDataWithSecret)

	return err
}

type NullableAppDataWithSecret struct {
	value *AppDataWithSecret
	isSet bool
}

func (v NullableAppDataWithSecret) Get() *AppDataWithSecret {
	return v.value
}

func (v *NullableAppDataWithSecret) Set(val *AppDataWithSecret) {
	v.value = val
	v.isSet = true
}

func (v NullableAppDataWithSecret) IsSet() bool {
	return v.isSet
}

func (v *NullableAppDataWithSecret) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAppDataWithSecret(val *AppDataWithSecret) *NullableAppDataWithSecret {
	return &NullableAppDataWithSecret{value: val, isSet: true}
}

func (v NullableAppDataWithSecret) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAppDataWithSecret) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


