/*
Snyk API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: REST
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateOrgServiceAccountRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateOrgServiceAccountRequest{}

// CreateOrgServiceAccountRequest struct for CreateOrgServiceAccountRequest
type CreateOrgServiceAccountRequest struct {
	Data CreateOrgServiceAccountRequestData `json:"data"`
}

type _CreateOrgServiceAccountRequest CreateOrgServiceAccountRequest

// NewCreateOrgServiceAccountRequest instantiates a new CreateOrgServiceAccountRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateOrgServiceAccountRequest(data CreateOrgServiceAccountRequestData) *CreateOrgServiceAccountRequest {
	this := CreateOrgServiceAccountRequest{}
	this.Data = data
	return &this
}

// NewCreateOrgServiceAccountRequestWithDefaults instantiates a new CreateOrgServiceAccountRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateOrgServiceAccountRequestWithDefaults() *CreateOrgServiceAccountRequest {
	this := CreateOrgServiceAccountRequest{}
	return &this
}

// GetData returns the Data field value
func (o *CreateOrgServiceAccountRequest) GetData() CreateOrgServiceAccountRequestData {
	if o == nil {
		var ret CreateOrgServiceAccountRequestData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *CreateOrgServiceAccountRequest) GetDataOk() (*CreateOrgServiceAccountRequestData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *CreateOrgServiceAccountRequest) SetData(v CreateOrgServiceAccountRequestData) {
	o.Data = v
}

func (o CreateOrgServiceAccountRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateOrgServiceAccountRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *CreateOrgServiceAccountRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateOrgServiceAccountRequest := _CreateOrgServiceAccountRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateOrgServiceAccountRequest)

	if err != nil {
		return err
	}

	*o = CreateOrgServiceAccountRequest(varCreateOrgServiceAccountRequest)

	return err
}

type NullableCreateOrgServiceAccountRequest struct {
	value *CreateOrgServiceAccountRequest
	isSet bool
}

func (v NullableCreateOrgServiceAccountRequest) Get() *CreateOrgServiceAccountRequest {
	return v.value
}

func (v *NullableCreateOrgServiceAccountRequest) Set(val *CreateOrgServiceAccountRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateOrgServiceAccountRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateOrgServiceAccountRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateOrgServiceAccountRequest(val *CreateOrgServiceAccountRequest) *NullableCreateOrgServiceAccountRequest {
	return &NullableCreateOrgServiceAccountRequest{value: val, isSet: true}
}

func (v NullableCreateOrgServiceAccountRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateOrgServiceAccountRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


