/*
Snyk API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: REST
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ListChannels200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListChannels200Response{}

// ListChannels200Response struct for ListChannels200Response
type ListChannels200Response struct {
	Data []SlackChannel `json:"data"`
	Jsonapi JsonApi `json:"jsonapi"`
	Links PaginatedLinks `json:"links"`
}

type _ListChannels200Response ListChannels200Response

// NewListChannels200Response instantiates a new ListChannels200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListChannels200Response(data []SlackChannel, jsonapi JsonApi, links PaginatedLinks) *ListChannels200Response {
	this := ListChannels200Response{}
	this.Data = data
	this.Jsonapi = jsonapi
	this.Links = links
	return &this
}

// NewListChannels200ResponseWithDefaults instantiates a new ListChannels200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListChannels200ResponseWithDefaults() *ListChannels200Response {
	this := ListChannels200Response{}
	return &this
}

// GetData returns the Data field value
func (o *ListChannels200Response) GetData() []SlackChannel {
	if o == nil {
		var ret []SlackChannel
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *ListChannels200Response) GetDataOk() ([]SlackChannel, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *ListChannels200Response) SetData(v []SlackChannel) {
	o.Data = v
}

// GetJsonapi returns the Jsonapi field value
func (o *ListChannels200Response) GetJsonapi() JsonApi {
	if o == nil {
		var ret JsonApi
		return ret
	}

	return o.Jsonapi
}

// GetJsonapiOk returns a tuple with the Jsonapi field value
// and a boolean to check if the value has been set.
func (o *ListChannels200Response) GetJsonapiOk() (*JsonApi, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Jsonapi, true
}

// SetJsonapi sets field value
func (o *ListChannels200Response) SetJsonapi(v JsonApi) {
	o.Jsonapi = v
}

// GetLinks returns the Links field value
func (o *ListChannels200Response) GetLinks() PaginatedLinks {
	if o == nil {
		var ret PaginatedLinks
		return ret
	}

	return o.Links
}

// GetLinksOk returns a tuple with the Links field value
// and a boolean to check if the value has been set.
func (o *ListChannels200Response) GetLinksOk() (*PaginatedLinks, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Links, true
}

// SetLinks sets field value
func (o *ListChannels200Response) SetLinks(v PaginatedLinks) {
	o.Links = v
}

func (o ListChannels200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListChannels200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	toSerialize["jsonapi"] = o.Jsonapi
	toSerialize["links"] = o.Links
	return toSerialize, nil
}

func (o *ListChannels200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
		"jsonapi",
		"links",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varListChannels200Response := _ListChannels200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varListChannels200Response)

	if err != nil {
		return err
	}

	*o = ListChannels200Response(varListChannels200Response)

	return err
}

type NullableListChannels200Response struct {
	value *ListChannels200Response
	isSet bool
}

func (v NullableListChannels200Response) Get() *ListChannels200Response {
	return v.value
}

func (v *NullableListChannels200Response) Set(val *ListChannels200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableListChannels200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableListChannels200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListChannels200Response(val *ListChannels200Response) *NullableListChannels200Response {
	return &NullableListChannels200Response{value: val, isSet: true}
}

func (v NullableListChannels200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListChannels200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


