/*
Snyk API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: REST
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AppInstallWithClient type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AppInstallWithClient{}

// AppInstallWithClient struct for AppInstallWithClient
type AppInstallWithClient struct {
	Attributes AppInstallWithClientAttributes `json:"attributes"`
	Id string `json:"id"`
	Links *Links `json:"links,omitempty"`
	Relationships AppInstallWithClientRelationships `json:"relationships"`
	Type string `json:"type"`
}

type _AppInstallWithClient AppInstallWithClient

// NewAppInstallWithClient instantiates a new AppInstallWithClient object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAppInstallWithClient(attributes AppInstallWithClientAttributes, id string, relationships AppInstallWithClientRelationships, type_ string) *AppInstallWithClient {
	this := AppInstallWithClient{}
	this.Attributes = attributes
	this.Id = id
	this.Relationships = relationships
	this.Type = type_
	return &this
}

// NewAppInstallWithClientWithDefaults instantiates a new AppInstallWithClient object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAppInstallWithClientWithDefaults() *AppInstallWithClient {
	this := AppInstallWithClient{}
	return &this
}

// GetAttributes returns the Attributes field value
func (o *AppInstallWithClient) GetAttributes() AppInstallWithClientAttributes {
	if o == nil {
		var ret AppInstallWithClientAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *AppInstallWithClient) GetAttributesOk() (*AppInstallWithClientAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *AppInstallWithClient) SetAttributes(v AppInstallWithClientAttributes) {
	o.Attributes = v
}

// GetId returns the Id field value
func (o *AppInstallWithClient) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *AppInstallWithClient) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *AppInstallWithClient) SetId(v string) {
	o.Id = v
}

// GetLinks returns the Links field value if set, zero value otherwise.
func (o *AppInstallWithClient) GetLinks() Links {
	if o == nil || IsNil(o.Links) {
		var ret Links
		return ret
	}
	return *o.Links
}

// GetLinksOk returns a tuple with the Links field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AppInstallWithClient) GetLinksOk() (*Links, bool) {
	if o == nil || IsNil(o.Links) {
		return nil, false
	}
	return o.Links, true
}

// HasLinks returns a boolean if a field has been set.
func (o *AppInstallWithClient) HasLinks() bool {
	if o != nil && !IsNil(o.Links) {
		return true
	}

	return false
}

// SetLinks gets a reference to the given Links and assigns it to the Links field.
func (o *AppInstallWithClient) SetLinks(v Links) {
	o.Links = &v
}

// GetRelationships returns the Relationships field value
func (o *AppInstallWithClient) GetRelationships() AppInstallWithClientRelationships {
	if o == nil {
		var ret AppInstallWithClientRelationships
		return ret
	}

	return o.Relationships
}

// GetRelationshipsOk returns a tuple with the Relationships field value
// and a boolean to check if the value has been set.
func (o *AppInstallWithClient) GetRelationshipsOk() (*AppInstallWithClientRelationships, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Relationships, true
}

// SetRelationships sets field value
func (o *AppInstallWithClient) SetRelationships(v AppInstallWithClientRelationships) {
	o.Relationships = v
}

// GetType returns the Type field value
func (o *AppInstallWithClient) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *AppInstallWithClient) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *AppInstallWithClient) SetType(v string) {
	o.Type = v
}

func (o AppInstallWithClient) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AppInstallWithClient) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["attributes"] = o.Attributes
	toSerialize["id"] = o.Id
	if !IsNil(o.Links) {
		toSerialize["links"] = o.Links
	}
	toSerialize["relationships"] = o.Relationships
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

func (o *AppInstallWithClient) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"attributes",
		"id",
		"relationships",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAppInstallWithClient := _AppInstallWithClient{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAppInstallWithClient)

	if err != nil {
		return err
	}

	*o = AppInstallWithClient(varAppInstallWithClient)

	return err
}

type NullableAppInstallWithClient struct {
	value *AppInstallWithClient
	isSet bool
}

func (v NullableAppInstallWithClient) Get() *AppInstallWithClient {
	return v.value
}

func (v *NullableAppInstallWithClient) Set(val *AppInstallWithClient) {
	v.value = val
	v.isSet = true
}

func (v NullableAppInstallWithClient) IsSet() bool {
	return v.isSet
}

func (v *NullableAppInstallWithClient) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAppInstallWithClient(val *AppInstallWithClient) *NullableAppInstallWithClient {
	return &NullableAppInstallWithClient{value: val, isSet: true}
}

func (v NullableAppInstallWithClient) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAppInstallWithClient) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


