/*
Snyk API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: REST
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UpdateGroupAppInstallSecretRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateGroupAppInstallSecretRequest{}

// UpdateGroupAppInstallSecretRequest struct for UpdateGroupAppInstallSecretRequest
type UpdateGroupAppInstallSecretRequest struct {
	Data UpdateGroupAppInstallSecretRequestData `json:"data"`
}

type _UpdateGroupAppInstallSecretRequest UpdateGroupAppInstallSecretRequest

// NewUpdateGroupAppInstallSecretRequest instantiates a new UpdateGroupAppInstallSecretRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateGroupAppInstallSecretRequest(data UpdateGroupAppInstallSecretRequestData) *UpdateGroupAppInstallSecretRequest {
	this := UpdateGroupAppInstallSecretRequest{}
	this.Data = data
	return &this
}

// NewUpdateGroupAppInstallSecretRequestWithDefaults instantiates a new UpdateGroupAppInstallSecretRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateGroupAppInstallSecretRequestWithDefaults() *UpdateGroupAppInstallSecretRequest {
	this := UpdateGroupAppInstallSecretRequest{}
	return &this
}

// GetData returns the Data field value
func (o *UpdateGroupAppInstallSecretRequest) GetData() UpdateGroupAppInstallSecretRequestData {
	if o == nil {
		var ret UpdateGroupAppInstallSecretRequestData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *UpdateGroupAppInstallSecretRequest) GetDataOk() (*UpdateGroupAppInstallSecretRequestData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *UpdateGroupAppInstallSecretRequest) SetData(v UpdateGroupAppInstallSecretRequestData) {
	o.Data = v
}

func (o UpdateGroupAppInstallSecretRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateGroupAppInstallSecretRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *UpdateGroupAppInstallSecretRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateGroupAppInstallSecretRequest := _UpdateGroupAppInstallSecretRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateGroupAppInstallSecretRequest)

	if err != nil {
		return err
	}

	*o = UpdateGroupAppInstallSecretRequest(varUpdateGroupAppInstallSecretRequest)

	return err
}

type NullableUpdateGroupAppInstallSecretRequest struct {
	value *UpdateGroupAppInstallSecretRequest
	isSet bool
}

func (v NullableUpdateGroupAppInstallSecretRequest) Get() *UpdateGroupAppInstallSecretRequest {
	return v.value
}

func (v *NullableUpdateGroupAppInstallSecretRequest) Set(val *UpdateGroupAppInstallSecretRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateGroupAppInstallSecretRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateGroupAppInstallSecretRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateGroupAppInstallSecretRequest(val *UpdateGroupAppInstallSecretRequest) *NullableUpdateGroupAppInstallSecretRequest {
	return &NullableUpdateGroupAppInstallSecretRequest{value: val, isSet: true}
}

func (v NullableUpdateGroupAppInstallSecretRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateGroupAppInstallSecretRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


