/*
Snyk API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: REST
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the AppPostResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AppPostResponse{}

// AppPostResponse struct for AppPostResponse
type AppPostResponse struct {
	Data *AppDataWithSecret `json:"data,omitempty"`
	Jsonapi *JsonApi `json:"jsonapi,omitempty"`
	Links *SelfLink `json:"links,omitempty"`
}

// NewAppPostResponse instantiates a new AppPostResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAppPostResponse() *AppPostResponse {
	this := AppPostResponse{}
	return &this
}

// NewAppPostResponseWithDefaults instantiates a new AppPostResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAppPostResponseWithDefaults() *AppPostResponse {
	this := AppPostResponse{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *AppPostResponse) GetData() AppDataWithSecret {
	if o == nil || IsNil(o.Data) {
		var ret AppDataWithSecret
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AppPostResponse) GetDataOk() (*AppDataWithSecret, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *AppPostResponse) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given AppDataWithSecret and assigns it to the Data field.
func (o *AppPostResponse) SetData(v AppDataWithSecret) {
	o.Data = &v
}

// GetJsonapi returns the Jsonapi field value if set, zero value otherwise.
func (o *AppPostResponse) GetJsonapi() JsonApi {
	if o == nil || IsNil(o.Jsonapi) {
		var ret JsonApi
		return ret
	}
	return *o.Jsonapi
}

// GetJsonapiOk returns a tuple with the Jsonapi field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AppPostResponse) GetJsonapiOk() (*JsonApi, bool) {
	if o == nil || IsNil(o.Jsonapi) {
		return nil, false
	}
	return o.Jsonapi, true
}

// HasJsonapi returns a boolean if a field has been set.
func (o *AppPostResponse) HasJsonapi() bool {
	if o != nil && !IsNil(o.Jsonapi) {
		return true
	}

	return false
}

// SetJsonapi gets a reference to the given JsonApi and assigns it to the Jsonapi field.
func (o *AppPostResponse) SetJsonapi(v JsonApi) {
	o.Jsonapi = &v
}

// GetLinks returns the Links field value if set, zero value otherwise.
func (o *AppPostResponse) GetLinks() SelfLink {
	if o == nil || IsNil(o.Links) {
		var ret SelfLink
		return ret
	}
	return *o.Links
}

// GetLinksOk returns a tuple with the Links field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AppPostResponse) GetLinksOk() (*SelfLink, bool) {
	if o == nil || IsNil(o.Links) {
		return nil, false
	}
	return o.Links, true
}

// HasLinks returns a boolean if a field has been set.
func (o *AppPostResponse) HasLinks() bool {
	if o != nil && !IsNil(o.Links) {
		return true
	}

	return false
}

// SetLinks gets a reference to the given SelfLink and assigns it to the Links field.
func (o *AppPostResponse) SetLinks(v SelfLink) {
	o.Links = &v
}

func (o AppPostResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AppPostResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.Jsonapi) {
		toSerialize["jsonapi"] = o.Jsonapi
	}
	if !IsNil(o.Links) {
		toSerialize["links"] = o.Links
	}
	return toSerialize, nil
}

type NullableAppPostResponse struct {
	value *AppPostResponse
	isSet bool
}

func (v NullableAppPostResponse) Get() *AppPostResponse {
	return v.value
}

func (v *NullableAppPostResponse) Set(val *AppPostResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAppPostResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAppPostResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAppPostResponse(val *AppPostResponse) *NullableAppPostResponse {
	return &NullableAppPostResponse{value: val, isSet: true}
}

func (v NullableAppPostResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAppPostResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


