/*
Snyk API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: REST
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GetProjectsOfCollectionResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetProjectsOfCollectionResponse{}

// GetProjectsOfCollectionResponse struct for GetProjectsOfCollectionResponse
type GetProjectsOfCollectionResponse struct {
	Data []ProjectOfCollection `json:"data,omitempty"`
	Jsonapi *JsonApi `json:"jsonapi,omitempty"`
	Links *PaginatedLinks `json:"links,omitempty"`
}

// NewGetProjectsOfCollectionResponse instantiates a new GetProjectsOfCollectionResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetProjectsOfCollectionResponse() *GetProjectsOfCollectionResponse {
	this := GetProjectsOfCollectionResponse{}
	return &this
}

// NewGetProjectsOfCollectionResponseWithDefaults instantiates a new GetProjectsOfCollectionResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetProjectsOfCollectionResponseWithDefaults() *GetProjectsOfCollectionResponse {
	this := GetProjectsOfCollectionResponse{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *GetProjectsOfCollectionResponse) GetData() []ProjectOfCollection {
	if o == nil || IsNil(o.Data) {
		var ret []ProjectOfCollection
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetProjectsOfCollectionResponse) GetDataOk() ([]ProjectOfCollection, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *GetProjectsOfCollectionResponse) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []ProjectOfCollection and assigns it to the Data field.
func (o *GetProjectsOfCollectionResponse) SetData(v []ProjectOfCollection) {
	o.Data = v
}

// GetJsonapi returns the Jsonapi field value if set, zero value otherwise.
func (o *GetProjectsOfCollectionResponse) GetJsonapi() JsonApi {
	if o == nil || IsNil(o.Jsonapi) {
		var ret JsonApi
		return ret
	}
	return *o.Jsonapi
}

// GetJsonapiOk returns a tuple with the Jsonapi field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetProjectsOfCollectionResponse) GetJsonapiOk() (*JsonApi, bool) {
	if o == nil || IsNil(o.Jsonapi) {
		return nil, false
	}
	return o.Jsonapi, true
}

// HasJsonapi returns a boolean if a field has been set.
func (o *GetProjectsOfCollectionResponse) HasJsonapi() bool {
	if o != nil && !IsNil(o.Jsonapi) {
		return true
	}

	return false
}

// SetJsonapi gets a reference to the given JsonApi and assigns it to the Jsonapi field.
func (o *GetProjectsOfCollectionResponse) SetJsonapi(v JsonApi) {
	o.Jsonapi = &v
}

// GetLinks returns the Links field value if set, zero value otherwise.
func (o *GetProjectsOfCollectionResponse) GetLinks() PaginatedLinks {
	if o == nil || IsNil(o.Links) {
		var ret PaginatedLinks
		return ret
	}
	return *o.Links
}

// GetLinksOk returns a tuple with the Links field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetProjectsOfCollectionResponse) GetLinksOk() (*PaginatedLinks, bool) {
	if o == nil || IsNil(o.Links) {
		return nil, false
	}
	return o.Links, true
}

// HasLinks returns a boolean if a field has been set.
func (o *GetProjectsOfCollectionResponse) HasLinks() bool {
	if o != nil && !IsNil(o.Links) {
		return true
	}

	return false
}

// SetLinks gets a reference to the given PaginatedLinks and assigns it to the Links field.
func (o *GetProjectsOfCollectionResponse) SetLinks(v PaginatedLinks) {
	o.Links = &v
}

func (o GetProjectsOfCollectionResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetProjectsOfCollectionResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.Jsonapi) {
		toSerialize["jsonapi"] = o.Jsonapi
	}
	if !IsNil(o.Links) {
		toSerialize["links"] = o.Links
	}
	return toSerialize, nil
}

type NullableGetProjectsOfCollectionResponse struct {
	value *GetProjectsOfCollectionResponse
	isSet bool
}

func (v NullableGetProjectsOfCollectionResponse) Get() *GetProjectsOfCollectionResponse {
	return v.value
}

func (v *NullableGetProjectsOfCollectionResponse) Set(val *GetProjectsOfCollectionResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetProjectsOfCollectionResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetProjectsOfCollectionResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetProjectsOfCollectionResponse(val *GetProjectsOfCollectionResponse) *NullableGetProjectsOfCollectionResponse {
	return &NullableGetProjectsOfCollectionResponse{value: val, isSet: true}
}

func (v NullableGetProjectsOfCollectionResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetProjectsOfCollectionResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


