/*
Snyk API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: REST
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UpdateGroupAppInstallSecretRequestData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateGroupAppInstallSecretRequestData{}

// UpdateGroupAppInstallSecretRequestData struct for UpdateGroupAppInstallSecretRequestData
type UpdateGroupAppInstallSecretRequestData struct {
	Attributes UpdateGroupAppInstallSecretRequestDataAttributes `json:"attributes"`
	Type string `json:"type"`
}

type _UpdateGroupAppInstallSecretRequestData UpdateGroupAppInstallSecretRequestData

// NewUpdateGroupAppInstallSecretRequestData instantiates a new UpdateGroupAppInstallSecretRequestData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateGroupAppInstallSecretRequestData(attributes UpdateGroupAppInstallSecretRequestDataAttributes, type_ string) *UpdateGroupAppInstallSecretRequestData {
	this := UpdateGroupAppInstallSecretRequestData{}
	this.Attributes = attributes
	this.Type = type_
	return &this
}

// NewUpdateGroupAppInstallSecretRequestDataWithDefaults instantiates a new UpdateGroupAppInstallSecretRequestData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateGroupAppInstallSecretRequestDataWithDefaults() *UpdateGroupAppInstallSecretRequestData {
	this := UpdateGroupAppInstallSecretRequestData{}
	return &this
}

// GetAttributes returns the Attributes field value
func (o *UpdateGroupAppInstallSecretRequestData) GetAttributes() UpdateGroupAppInstallSecretRequestDataAttributes {
	if o == nil {
		var ret UpdateGroupAppInstallSecretRequestDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *UpdateGroupAppInstallSecretRequestData) GetAttributesOk() (*UpdateGroupAppInstallSecretRequestDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *UpdateGroupAppInstallSecretRequestData) SetAttributes(v UpdateGroupAppInstallSecretRequestDataAttributes) {
	o.Attributes = v
}

// GetType returns the Type field value
func (o *UpdateGroupAppInstallSecretRequestData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *UpdateGroupAppInstallSecretRequestData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *UpdateGroupAppInstallSecretRequestData) SetType(v string) {
	o.Type = v
}

func (o UpdateGroupAppInstallSecretRequestData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateGroupAppInstallSecretRequestData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["attributes"] = o.Attributes
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

func (o *UpdateGroupAppInstallSecretRequestData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"attributes",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateGroupAppInstallSecretRequestData := _UpdateGroupAppInstallSecretRequestData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateGroupAppInstallSecretRequestData)

	if err != nil {
		return err
	}

	*o = UpdateGroupAppInstallSecretRequestData(varUpdateGroupAppInstallSecretRequestData)

	return err
}

type NullableUpdateGroupAppInstallSecretRequestData struct {
	value *UpdateGroupAppInstallSecretRequestData
	isSet bool
}

func (v NullableUpdateGroupAppInstallSecretRequestData) Get() *UpdateGroupAppInstallSecretRequestData {
	return v.value
}

func (v *NullableUpdateGroupAppInstallSecretRequestData) Set(val *UpdateGroupAppInstallSecretRequestData) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateGroupAppInstallSecretRequestData) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateGroupAppInstallSecretRequestData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateGroupAppInstallSecretRequestData(val *UpdateGroupAppInstallSecretRequestData) *NullableUpdateGroupAppInstallSecretRequestData {
	return &NullableUpdateGroupAppInstallSecretRequestData{value: val, isSet: true}
}

func (v NullableUpdateGroupAppInstallSecretRequestData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateGroupAppInstallSecretRequestData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


