/*
Snyk API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: REST
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the CreateCollection201Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateCollection201Response{}

// CreateCollection201Response struct for CreateCollection201Response
type CreateCollection201Response struct {
	Data *CreateCollection201ResponseData `json:"data,omitempty"`
	Jsonapi *JsonApi `json:"jsonapi,omitempty"`
	Links *SelfLink `json:"links,omitempty"`
}

// NewCreateCollection201Response instantiates a new CreateCollection201Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateCollection201Response() *CreateCollection201Response {
	this := CreateCollection201Response{}
	return &this
}

// NewCreateCollection201ResponseWithDefaults instantiates a new CreateCollection201Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateCollection201ResponseWithDefaults() *CreateCollection201Response {
	this := CreateCollection201Response{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *CreateCollection201Response) GetData() CreateCollection201ResponseData {
	if o == nil || IsNil(o.Data) {
		var ret CreateCollection201ResponseData
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateCollection201Response) GetDataOk() (*CreateCollection201ResponseData, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *CreateCollection201Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given CreateCollection201ResponseData and assigns it to the Data field.
func (o *CreateCollection201Response) SetData(v CreateCollection201ResponseData) {
	o.Data = &v
}

// GetJsonapi returns the Jsonapi field value if set, zero value otherwise.
func (o *CreateCollection201Response) GetJsonapi() JsonApi {
	if o == nil || IsNil(o.Jsonapi) {
		var ret JsonApi
		return ret
	}
	return *o.Jsonapi
}

// GetJsonapiOk returns a tuple with the Jsonapi field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateCollection201Response) GetJsonapiOk() (*JsonApi, bool) {
	if o == nil || IsNil(o.Jsonapi) {
		return nil, false
	}
	return o.Jsonapi, true
}

// HasJsonapi returns a boolean if a field has been set.
func (o *CreateCollection201Response) HasJsonapi() bool {
	if o != nil && !IsNil(o.Jsonapi) {
		return true
	}

	return false
}

// SetJsonapi gets a reference to the given JsonApi and assigns it to the Jsonapi field.
func (o *CreateCollection201Response) SetJsonapi(v JsonApi) {
	o.Jsonapi = &v
}

// GetLinks returns the Links field value if set, zero value otherwise.
func (o *CreateCollection201Response) GetLinks() SelfLink {
	if o == nil || IsNil(o.Links) {
		var ret SelfLink
		return ret
	}
	return *o.Links
}

// GetLinksOk returns a tuple with the Links field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateCollection201Response) GetLinksOk() (*SelfLink, bool) {
	if o == nil || IsNil(o.Links) {
		return nil, false
	}
	return o.Links, true
}

// HasLinks returns a boolean if a field has been set.
func (o *CreateCollection201Response) HasLinks() bool {
	if o != nil && !IsNil(o.Links) {
		return true
	}

	return false
}

// SetLinks gets a reference to the given SelfLink and assigns it to the Links field.
func (o *CreateCollection201Response) SetLinks(v SelfLink) {
	o.Links = &v
}

func (o CreateCollection201Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateCollection201Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.Jsonapi) {
		toSerialize["jsonapi"] = o.Jsonapi
	}
	if !IsNil(o.Links) {
		toSerialize["links"] = o.Links
	}
	return toSerialize, nil
}

type NullableCreateCollection201Response struct {
	value *CreateCollection201Response
	isSet bool
}

func (v NullableCreateCollection201Response) Get() *CreateCollection201Response {
	return v.value
}

func (v *NullableCreateCollection201Response) Set(val *CreateCollection201Response) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateCollection201Response) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateCollection201Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateCollection201Response(val *CreateCollection201Response) *NullableCreateCollection201Response {
	return &NullableCreateCollection201Response{value: val, isSet: true}
}

func (v NullableCreateCollection201Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateCollection201Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


