/*
Snyk API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: REST
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PublicAppData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PublicAppData{}

// PublicAppData struct for PublicAppData
type PublicAppData struct {
	Attributes *PublicAppDataAttributes `json:"attributes,omitempty"`
	Id string `json:"id"`
	Links *Links `json:"links,omitempty"`
	Type string `json:"type"`
}

type _PublicAppData PublicAppData

// NewPublicAppData instantiates a new PublicAppData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPublicAppData(id string, type_ string) *PublicAppData {
	this := PublicAppData{}
	this.Id = id
	this.Type = type_
	return &this
}

// NewPublicAppDataWithDefaults instantiates a new PublicAppData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPublicAppDataWithDefaults() *PublicAppData {
	this := PublicAppData{}
	return &this
}

// GetAttributes returns the Attributes field value if set, zero value otherwise.
func (o *PublicAppData) GetAttributes() PublicAppDataAttributes {
	if o == nil || IsNil(o.Attributes) {
		var ret PublicAppDataAttributes
		return ret
	}
	return *o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PublicAppData) GetAttributesOk() (*PublicAppDataAttributes, bool) {
	if o == nil || IsNil(o.Attributes) {
		return nil, false
	}
	return o.Attributes, true
}

// HasAttributes returns a boolean if a field has been set.
func (o *PublicAppData) HasAttributes() bool {
	if o != nil && !IsNil(o.Attributes) {
		return true
	}

	return false
}

// SetAttributes gets a reference to the given PublicAppDataAttributes and assigns it to the Attributes field.
func (o *PublicAppData) SetAttributes(v PublicAppDataAttributes) {
	o.Attributes = &v
}

// GetId returns the Id field value
func (o *PublicAppData) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *PublicAppData) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *PublicAppData) SetId(v string) {
	o.Id = v
}

// GetLinks returns the Links field value if set, zero value otherwise.
func (o *PublicAppData) GetLinks() Links {
	if o == nil || IsNil(o.Links) {
		var ret Links
		return ret
	}
	return *o.Links
}

// GetLinksOk returns a tuple with the Links field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PublicAppData) GetLinksOk() (*Links, bool) {
	if o == nil || IsNil(o.Links) {
		return nil, false
	}
	return o.Links, true
}

// HasLinks returns a boolean if a field has been set.
func (o *PublicAppData) HasLinks() bool {
	if o != nil && !IsNil(o.Links) {
		return true
	}

	return false
}

// SetLinks gets a reference to the given Links and assigns it to the Links field.
func (o *PublicAppData) SetLinks(v Links) {
	o.Links = &v
}

// GetType returns the Type field value
func (o *PublicAppData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *PublicAppData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *PublicAppData) SetType(v string) {
	o.Type = v
}

func (o PublicAppData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PublicAppData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Attributes) {
		toSerialize["attributes"] = o.Attributes
	}
	toSerialize["id"] = o.Id
	if !IsNil(o.Links) {
		toSerialize["links"] = o.Links
	}
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

func (o *PublicAppData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPublicAppData := _PublicAppData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPublicAppData)

	if err != nil {
		return err
	}

	*o = PublicAppData(varPublicAppData)

	return err
}

type NullablePublicAppData struct {
	value *PublicAppData
	isSet bool
}

func (v NullablePublicAppData) Get() *PublicAppData {
	return v.value
}

func (v *NullablePublicAppData) Set(val *PublicAppData) {
	v.value = val
	v.isSet = true
}

func (v NullablePublicAppData) IsSet() bool {
	return v.isSet
}

func (v *NullablePublicAppData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePublicAppData(val *PublicAppData) *NullablePublicAppData {
	return &NullablePublicAppData{value: val, isSet: true}
}

func (v NullablePublicAppData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePublicAppData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


