/*
Snyk API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: REST
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UpdateGroupServiceAccountRequestDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateGroupServiceAccountRequestDataAttributes{}

// UpdateGroupServiceAccountRequestDataAttributes struct for UpdateGroupServiceAccountRequestDataAttributes
type UpdateGroupServiceAccountRequestDataAttributes struct {
	// A human-friendly name for the service account. Must be unique within the group.
	Name string `json:"name"`
}

type _UpdateGroupServiceAccountRequestDataAttributes UpdateGroupServiceAccountRequestDataAttributes

// NewUpdateGroupServiceAccountRequestDataAttributes instantiates a new UpdateGroupServiceAccountRequestDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateGroupServiceAccountRequestDataAttributes(name string) *UpdateGroupServiceAccountRequestDataAttributes {
	this := UpdateGroupServiceAccountRequestDataAttributes{}
	this.Name = name
	return &this
}

// NewUpdateGroupServiceAccountRequestDataAttributesWithDefaults instantiates a new UpdateGroupServiceAccountRequestDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateGroupServiceAccountRequestDataAttributesWithDefaults() *UpdateGroupServiceAccountRequestDataAttributes {
	this := UpdateGroupServiceAccountRequestDataAttributes{}
	return &this
}

// GetName returns the Name field value
func (o *UpdateGroupServiceAccountRequestDataAttributes) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *UpdateGroupServiceAccountRequestDataAttributes) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *UpdateGroupServiceAccountRequestDataAttributes) SetName(v string) {
	o.Name = v
}

func (o UpdateGroupServiceAccountRequestDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateGroupServiceAccountRequestDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	return toSerialize, nil
}

func (o *UpdateGroupServiceAccountRequestDataAttributes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateGroupServiceAccountRequestDataAttributes := _UpdateGroupServiceAccountRequestDataAttributes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateGroupServiceAccountRequestDataAttributes)

	if err != nil {
		return err
	}

	*o = UpdateGroupServiceAccountRequestDataAttributes(varUpdateGroupServiceAccountRequestDataAttributes)

	return err
}

type NullableUpdateGroupServiceAccountRequestDataAttributes struct {
	value *UpdateGroupServiceAccountRequestDataAttributes
	isSet bool
}

func (v NullableUpdateGroupServiceAccountRequestDataAttributes) Get() *UpdateGroupServiceAccountRequestDataAttributes {
	return v.value
}

func (v *NullableUpdateGroupServiceAccountRequestDataAttributes) Set(val *UpdateGroupServiceAccountRequestDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateGroupServiceAccountRequestDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateGroupServiceAccountRequestDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateGroupServiceAccountRequestDataAttributes(val *UpdateGroupServiceAccountRequestDataAttributes) *NullableUpdateGroupServiceAccountRequestDataAttributes {
	return &NullableUpdateGroupServiceAccountRequestDataAttributes{value: val, isSet: true}
}

func (v NullableUpdateGroupServiceAccountRequestDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateGroupServiceAccountRequestDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


