/*
Snyk API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: REST
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ProjectOfCollection type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProjectOfCollection{}

// ProjectOfCollection struct for ProjectOfCollection
type ProjectOfCollection struct {
	Id string `json:"id"`
	Meta ProjectMeta `json:"meta"`
	Relationships ProjectOfCollectionRelationships `json:"relationships"`
	Type string `json:"type"`
}

type _ProjectOfCollection ProjectOfCollection

// NewProjectOfCollection instantiates a new ProjectOfCollection object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProjectOfCollection(id string, meta ProjectMeta, relationships ProjectOfCollectionRelationships, type_ string) *ProjectOfCollection {
	this := ProjectOfCollection{}
	this.Id = id
	this.Meta = meta
	this.Relationships = relationships
	this.Type = type_
	return &this
}

// NewProjectOfCollectionWithDefaults instantiates a new ProjectOfCollection object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProjectOfCollectionWithDefaults() *ProjectOfCollection {
	this := ProjectOfCollection{}
	return &this
}

// GetId returns the Id field value
func (o *ProjectOfCollection) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ProjectOfCollection) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ProjectOfCollection) SetId(v string) {
	o.Id = v
}

// GetMeta returns the Meta field value
func (o *ProjectOfCollection) GetMeta() ProjectMeta {
	if o == nil {
		var ret ProjectMeta
		return ret
	}

	return o.Meta
}

// GetMetaOk returns a tuple with the Meta field value
// and a boolean to check if the value has been set.
func (o *ProjectOfCollection) GetMetaOk() (*ProjectMeta, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Meta, true
}

// SetMeta sets field value
func (o *ProjectOfCollection) SetMeta(v ProjectMeta) {
	o.Meta = v
}

// GetRelationships returns the Relationships field value
func (o *ProjectOfCollection) GetRelationships() ProjectOfCollectionRelationships {
	if o == nil {
		var ret ProjectOfCollectionRelationships
		return ret
	}

	return o.Relationships
}

// GetRelationshipsOk returns a tuple with the Relationships field value
// and a boolean to check if the value has been set.
func (o *ProjectOfCollection) GetRelationshipsOk() (*ProjectOfCollectionRelationships, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Relationships, true
}

// SetRelationships sets field value
func (o *ProjectOfCollection) SetRelationships(v ProjectOfCollectionRelationships) {
	o.Relationships = v
}

// GetType returns the Type field value
func (o *ProjectOfCollection) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *ProjectOfCollection) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *ProjectOfCollection) SetType(v string) {
	o.Type = v
}

func (o ProjectOfCollection) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProjectOfCollection) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["meta"] = o.Meta
	toSerialize["relationships"] = o.Relationships
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

func (o *ProjectOfCollection) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"meta",
		"relationships",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varProjectOfCollection := _ProjectOfCollection{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varProjectOfCollection)

	if err != nil {
		return err
	}

	*o = ProjectOfCollection(varProjectOfCollection)

	return err
}

type NullableProjectOfCollection struct {
	value *ProjectOfCollection
	isSet bool
}

func (v NullableProjectOfCollection) Get() *ProjectOfCollection {
	return v.value
}

func (v *NullableProjectOfCollection) Set(val *ProjectOfCollection) {
	v.value = val
	v.isSet = true
}

func (v NullableProjectOfCollection) IsSet() bool {
	return v.isSet
}

func (v *NullableProjectOfCollection) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProjectOfCollection(val *ProjectOfCollection) *NullableProjectOfCollection {
	return &NullableProjectOfCollection{value: val, isSet: true}
}

func (v NullableProjectOfCollection) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProjectOfCollection) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


