/*
Snyk API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: REST
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GetManyGroupServiceAccount200ResponseDataInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetManyGroupServiceAccount200ResponseDataInner{}

// GetManyGroupServiceAccount200ResponseDataInner struct for GetManyGroupServiceAccount200ResponseDataInner
type GetManyGroupServiceAccount200ResponseDataInner struct {
	Attributes GetManyGroupServiceAccount200ResponseDataInnerAttributes `json:"attributes"`
	Id string `json:"id"`
	Links *GetManyGroupServiceAccount200ResponseDataInnerLinks `json:"links,omitempty"`
	Type string `json:"type"`
}

type _GetManyGroupServiceAccount200ResponseDataInner GetManyGroupServiceAccount200ResponseDataInner

// NewGetManyGroupServiceAccount200ResponseDataInner instantiates a new GetManyGroupServiceAccount200ResponseDataInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetManyGroupServiceAccount200ResponseDataInner(attributes GetManyGroupServiceAccount200ResponseDataInnerAttributes, id string, type_ string) *GetManyGroupServiceAccount200ResponseDataInner {
	this := GetManyGroupServiceAccount200ResponseDataInner{}
	this.Attributes = attributes
	this.Id = id
	this.Type = type_
	return &this
}

// NewGetManyGroupServiceAccount200ResponseDataInnerWithDefaults instantiates a new GetManyGroupServiceAccount200ResponseDataInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetManyGroupServiceAccount200ResponseDataInnerWithDefaults() *GetManyGroupServiceAccount200ResponseDataInner {
	this := GetManyGroupServiceAccount200ResponseDataInner{}
	return &this
}

// GetAttributes returns the Attributes field value
func (o *GetManyGroupServiceAccount200ResponseDataInner) GetAttributes() GetManyGroupServiceAccount200ResponseDataInnerAttributes {
	if o == nil {
		var ret GetManyGroupServiceAccount200ResponseDataInnerAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *GetManyGroupServiceAccount200ResponseDataInner) GetAttributesOk() (*GetManyGroupServiceAccount200ResponseDataInnerAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *GetManyGroupServiceAccount200ResponseDataInner) SetAttributes(v GetManyGroupServiceAccount200ResponseDataInnerAttributes) {
	o.Attributes = v
}

// GetId returns the Id field value
func (o *GetManyGroupServiceAccount200ResponseDataInner) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *GetManyGroupServiceAccount200ResponseDataInner) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *GetManyGroupServiceAccount200ResponseDataInner) SetId(v string) {
	o.Id = v
}

// GetLinks returns the Links field value if set, zero value otherwise.
func (o *GetManyGroupServiceAccount200ResponseDataInner) GetLinks() GetManyGroupServiceAccount200ResponseDataInnerLinks {
	if o == nil || IsNil(o.Links) {
		var ret GetManyGroupServiceAccount200ResponseDataInnerLinks
		return ret
	}
	return *o.Links
}

// GetLinksOk returns a tuple with the Links field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetManyGroupServiceAccount200ResponseDataInner) GetLinksOk() (*GetManyGroupServiceAccount200ResponseDataInnerLinks, bool) {
	if o == nil || IsNil(o.Links) {
		return nil, false
	}
	return o.Links, true
}

// HasLinks returns a boolean if a field has been set.
func (o *GetManyGroupServiceAccount200ResponseDataInner) HasLinks() bool {
	if o != nil && !IsNil(o.Links) {
		return true
	}

	return false
}

// SetLinks gets a reference to the given GetManyGroupServiceAccount200ResponseDataInnerLinks and assigns it to the Links field.
func (o *GetManyGroupServiceAccount200ResponseDataInner) SetLinks(v GetManyGroupServiceAccount200ResponseDataInnerLinks) {
	o.Links = &v
}

// GetType returns the Type field value
func (o *GetManyGroupServiceAccount200ResponseDataInner) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *GetManyGroupServiceAccount200ResponseDataInner) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *GetManyGroupServiceAccount200ResponseDataInner) SetType(v string) {
	o.Type = v
}

func (o GetManyGroupServiceAccount200ResponseDataInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetManyGroupServiceAccount200ResponseDataInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["attributes"] = o.Attributes
	toSerialize["id"] = o.Id
	if !IsNil(o.Links) {
		toSerialize["links"] = o.Links
	}
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

func (o *GetManyGroupServiceAccount200ResponseDataInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"attributes",
		"id",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetManyGroupServiceAccount200ResponseDataInner := _GetManyGroupServiceAccount200ResponseDataInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetManyGroupServiceAccount200ResponseDataInner)

	if err != nil {
		return err
	}

	*o = GetManyGroupServiceAccount200ResponseDataInner(varGetManyGroupServiceAccount200ResponseDataInner)

	return err
}

type NullableGetManyGroupServiceAccount200ResponseDataInner struct {
	value *GetManyGroupServiceAccount200ResponseDataInner
	isSet bool
}

func (v NullableGetManyGroupServiceAccount200ResponseDataInner) Get() *GetManyGroupServiceAccount200ResponseDataInner {
	return v.value
}

func (v *NullableGetManyGroupServiceAccount200ResponseDataInner) Set(val *GetManyGroupServiceAccount200ResponseDataInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGetManyGroupServiceAccount200ResponseDataInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGetManyGroupServiceAccount200ResponseDataInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetManyGroupServiceAccount200ResponseDataInner(val *GetManyGroupServiceAccount200ResponseDataInner) *NullableGetManyGroupServiceAccount200ResponseDataInner {
	return &NullableGetManyGroupServiceAccount200ResponseDataInner{value: val, isSet: true}
}

func (v NullableGetManyGroupServiceAccount200ResponseDataInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetManyGroupServiceAccount200ResponseDataInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


