/*
Snyk API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: REST
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
)

// checks if the ListOrgProjects200ResponseDataInnerMeta type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListOrgProjects200ResponseDataInnerMeta{}

// ListOrgProjects200ResponseDataInnerMeta struct for ListOrgProjects200ResponseDataInnerMeta
type ListOrgProjects200ResponseDataInnerMeta struct {
	// The date that the project was last uploaded and monitored using cli.
	CliMonitoredAt NullableTime `json:"cli_monitored_at,omitempty"`
	LatestDependencyTotal *LatestDependencyTotal `json:"latest_dependency_total,omitempty"`
	LatestIssueCounts *LatestIssueCounts `json:"latest_issue_counts,omitempty"`
}

// NewListOrgProjects200ResponseDataInnerMeta instantiates a new ListOrgProjects200ResponseDataInnerMeta object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListOrgProjects200ResponseDataInnerMeta() *ListOrgProjects200ResponseDataInnerMeta {
	this := ListOrgProjects200ResponseDataInnerMeta{}
	return &this
}

// NewListOrgProjects200ResponseDataInnerMetaWithDefaults instantiates a new ListOrgProjects200ResponseDataInnerMeta object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListOrgProjects200ResponseDataInnerMetaWithDefaults() *ListOrgProjects200ResponseDataInnerMeta {
	this := ListOrgProjects200ResponseDataInnerMeta{}
	return &this
}

// GetCliMonitoredAt returns the CliMonitoredAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ListOrgProjects200ResponseDataInnerMeta) GetCliMonitoredAt() time.Time {
	if o == nil || IsNil(o.CliMonitoredAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.CliMonitoredAt.Get()
}

// GetCliMonitoredAtOk returns a tuple with the CliMonitoredAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListOrgProjects200ResponseDataInnerMeta) GetCliMonitoredAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.CliMonitoredAt.Get(), o.CliMonitoredAt.IsSet()
}

// HasCliMonitoredAt returns a boolean if a field has been set.
func (o *ListOrgProjects200ResponseDataInnerMeta) HasCliMonitoredAt() bool {
	if o != nil && o.CliMonitoredAt.IsSet() {
		return true
	}

	return false
}

// SetCliMonitoredAt gets a reference to the given NullableTime and assigns it to the CliMonitoredAt field.
func (o *ListOrgProjects200ResponseDataInnerMeta) SetCliMonitoredAt(v time.Time) {
	o.CliMonitoredAt.Set(&v)
}
// SetCliMonitoredAtNil sets the value for CliMonitoredAt to be an explicit nil
func (o *ListOrgProjects200ResponseDataInnerMeta) SetCliMonitoredAtNil() {
	o.CliMonitoredAt.Set(nil)
}

// UnsetCliMonitoredAt ensures that no value is present for CliMonitoredAt, not even an explicit nil
func (o *ListOrgProjects200ResponseDataInnerMeta) UnsetCliMonitoredAt() {
	o.CliMonitoredAt.Unset()
}

// GetLatestDependencyTotal returns the LatestDependencyTotal field value if set, zero value otherwise.
func (o *ListOrgProjects200ResponseDataInnerMeta) GetLatestDependencyTotal() LatestDependencyTotal {
	if o == nil || IsNil(o.LatestDependencyTotal) {
		var ret LatestDependencyTotal
		return ret
	}
	return *o.LatestDependencyTotal
}

// GetLatestDependencyTotalOk returns a tuple with the LatestDependencyTotal field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListOrgProjects200ResponseDataInnerMeta) GetLatestDependencyTotalOk() (*LatestDependencyTotal, bool) {
	if o == nil || IsNil(o.LatestDependencyTotal) {
		return nil, false
	}
	return o.LatestDependencyTotal, true
}

// HasLatestDependencyTotal returns a boolean if a field has been set.
func (o *ListOrgProjects200ResponseDataInnerMeta) HasLatestDependencyTotal() bool {
	if o != nil && !IsNil(o.LatestDependencyTotal) {
		return true
	}

	return false
}

// SetLatestDependencyTotal gets a reference to the given LatestDependencyTotal and assigns it to the LatestDependencyTotal field.
func (o *ListOrgProjects200ResponseDataInnerMeta) SetLatestDependencyTotal(v LatestDependencyTotal) {
	o.LatestDependencyTotal = &v
}

// GetLatestIssueCounts returns the LatestIssueCounts field value if set, zero value otherwise.
func (o *ListOrgProjects200ResponseDataInnerMeta) GetLatestIssueCounts() LatestIssueCounts {
	if o == nil || IsNil(o.LatestIssueCounts) {
		var ret LatestIssueCounts
		return ret
	}
	return *o.LatestIssueCounts
}

// GetLatestIssueCountsOk returns a tuple with the LatestIssueCounts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListOrgProjects200ResponseDataInnerMeta) GetLatestIssueCountsOk() (*LatestIssueCounts, bool) {
	if o == nil || IsNil(o.LatestIssueCounts) {
		return nil, false
	}
	return o.LatestIssueCounts, true
}

// HasLatestIssueCounts returns a boolean if a field has been set.
func (o *ListOrgProjects200ResponseDataInnerMeta) HasLatestIssueCounts() bool {
	if o != nil && !IsNil(o.LatestIssueCounts) {
		return true
	}

	return false
}

// SetLatestIssueCounts gets a reference to the given LatestIssueCounts and assigns it to the LatestIssueCounts field.
func (o *ListOrgProjects200ResponseDataInnerMeta) SetLatestIssueCounts(v LatestIssueCounts) {
	o.LatestIssueCounts = &v
}

func (o ListOrgProjects200ResponseDataInnerMeta) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListOrgProjects200ResponseDataInnerMeta) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.CliMonitoredAt.IsSet() {
		toSerialize["cli_monitored_at"] = o.CliMonitoredAt.Get()
	}
	if !IsNil(o.LatestDependencyTotal) {
		toSerialize["latest_dependency_total"] = o.LatestDependencyTotal
	}
	if !IsNil(o.LatestIssueCounts) {
		toSerialize["latest_issue_counts"] = o.LatestIssueCounts
	}
	return toSerialize, nil
}

type NullableListOrgProjects200ResponseDataInnerMeta struct {
	value *ListOrgProjects200ResponseDataInnerMeta
	isSet bool
}

func (v NullableListOrgProjects200ResponseDataInnerMeta) Get() *ListOrgProjects200ResponseDataInnerMeta {
	return v.value
}

func (v *NullableListOrgProjects200ResponseDataInnerMeta) Set(val *ListOrgProjects200ResponseDataInnerMeta) {
	v.value = val
	v.isSet = true
}

func (v NullableListOrgProjects200ResponseDataInnerMeta) IsSet() bool {
	return v.isSet
}

func (v *NullableListOrgProjects200ResponseDataInnerMeta) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListOrgProjects200ResponseDataInnerMeta(val *ListOrgProjects200ResponseDataInnerMeta) *NullableListOrgProjects200ResponseDataInnerMeta {
	return &NullableListOrgProjects200ResponseDataInnerMeta{value: val, isSet: true}
}

func (v NullableListOrgProjects200ResponseDataInnerMeta) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListOrgProjects200ResponseDataInnerMeta) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


