/*
Snyk API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: REST
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GetIacSettingsForOrg200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetIacSettingsForOrg200Response{}

// GetIacSettingsForOrg200Response struct for GetIacSettingsForOrg200Response
type GetIacSettingsForOrg200Response struct {
	Data OrgIacSettingsResponse `json:"data"`
	Jsonapi JsonApi `json:"jsonapi"`
	Links Links `json:"links"`
}

type _GetIacSettingsForOrg200Response GetIacSettingsForOrg200Response

// NewGetIacSettingsForOrg200Response instantiates a new GetIacSettingsForOrg200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetIacSettingsForOrg200Response(data OrgIacSettingsResponse, jsonapi JsonApi, links Links) *GetIacSettingsForOrg200Response {
	this := GetIacSettingsForOrg200Response{}
	this.Data = data
	this.Jsonapi = jsonapi
	this.Links = links
	return &this
}

// NewGetIacSettingsForOrg200ResponseWithDefaults instantiates a new GetIacSettingsForOrg200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetIacSettingsForOrg200ResponseWithDefaults() *GetIacSettingsForOrg200Response {
	this := GetIacSettingsForOrg200Response{}
	return &this
}

// GetData returns the Data field value
func (o *GetIacSettingsForOrg200Response) GetData() OrgIacSettingsResponse {
	if o == nil {
		var ret OrgIacSettingsResponse
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *GetIacSettingsForOrg200Response) GetDataOk() (*OrgIacSettingsResponse, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *GetIacSettingsForOrg200Response) SetData(v OrgIacSettingsResponse) {
	o.Data = v
}

// GetJsonapi returns the Jsonapi field value
func (o *GetIacSettingsForOrg200Response) GetJsonapi() JsonApi {
	if o == nil {
		var ret JsonApi
		return ret
	}

	return o.Jsonapi
}

// GetJsonapiOk returns a tuple with the Jsonapi field value
// and a boolean to check if the value has been set.
func (o *GetIacSettingsForOrg200Response) GetJsonapiOk() (*JsonApi, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Jsonapi, true
}

// SetJsonapi sets field value
func (o *GetIacSettingsForOrg200Response) SetJsonapi(v JsonApi) {
	o.Jsonapi = v
}

// GetLinks returns the Links field value
func (o *GetIacSettingsForOrg200Response) GetLinks() Links {
	if o == nil {
		var ret Links
		return ret
	}

	return o.Links
}

// GetLinksOk returns a tuple with the Links field value
// and a boolean to check if the value has been set.
func (o *GetIacSettingsForOrg200Response) GetLinksOk() (*Links, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Links, true
}

// SetLinks sets field value
func (o *GetIacSettingsForOrg200Response) SetLinks(v Links) {
	o.Links = v
}

func (o GetIacSettingsForOrg200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetIacSettingsForOrg200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	toSerialize["jsonapi"] = o.Jsonapi
	toSerialize["links"] = o.Links
	return toSerialize, nil
}

func (o *GetIacSettingsForOrg200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
		"jsonapi",
		"links",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetIacSettingsForOrg200Response := _GetIacSettingsForOrg200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetIacSettingsForOrg200Response)

	if err != nil {
		return err
	}

	*o = GetIacSettingsForOrg200Response(varGetIacSettingsForOrg200Response)

	return err
}

type NullableGetIacSettingsForOrg200Response struct {
	value *GetIacSettingsForOrg200Response
	isSet bool
}

func (v NullableGetIacSettingsForOrg200Response) Get() *GetIacSettingsForOrg200Response {
	return v.value
}

func (v *NullableGetIacSettingsForOrg200Response) Set(val *GetIacSettingsForOrg200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetIacSettingsForOrg200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetIacSettingsForOrg200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetIacSettingsForOrg200Response(val *GetIacSettingsForOrg200Response) *NullableGetIacSettingsForOrg200Response {
	return &NullableGetIacSettingsForOrg200Response{value: val, isSet: true}
}

func (v NullableGetIacSettingsForOrg200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetIacSettingsForOrg200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


