/*
Snyk API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: REST
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
	// "bytes"
)

// GetManyGroupServiceAccount200ResponseDataInnerLinksFirst - struct for GetManyGroupServiceAccount200ResponseDataInnerLinksFirst
type GetManyGroupServiceAccount200ResponseDataInnerLinksFirst struct {
	GetManyGroupServiceAccount200ResponseDataInnerLinksFirstOneOf *GetManyGroupServiceAccount200ResponseDataInnerLinksFirstOneOf
	String *string
}

// GetManyGroupServiceAccount200ResponseDataInnerLinksFirstOneOfAsGetManyGroupServiceAccount200ResponseDataInnerLinksFirst is a convenience function that returns GetManyGroupServiceAccount200ResponseDataInnerLinksFirstOneOf wrapped in GetManyGroupServiceAccount200ResponseDataInnerLinksFirst
func GetManyGroupServiceAccount200ResponseDataInnerLinksFirstOneOfAsGetManyGroupServiceAccount200ResponseDataInnerLinksFirst(v *GetManyGroupServiceAccount200ResponseDataInnerLinksFirstOneOf) GetManyGroupServiceAccount200ResponseDataInnerLinksFirst {
	return GetManyGroupServiceAccount200ResponseDataInnerLinksFirst{
		GetManyGroupServiceAccount200ResponseDataInnerLinksFirstOneOf: v,
	}
}

// stringAsGetManyGroupServiceAccount200ResponseDataInnerLinksFirst is a convenience function that returns string wrapped in GetManyGroupServiceAccount200ResponseDataInnerLinksFirst
func StringAsGetManyGroupServiceAccount200ResponseDataInnerLinksFirst(v *string) GetManyGroupServiceAccount200ResponseDataInnerLinksFirst {
	return GetManyGroupServiceAccount200ResponseDataInnerLinksFirst{
		String: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *GetManyGroupServiceAccount200ResponseDataInnerLinksFirst) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into GetManyGroupServiceAccount200ResponseDataInnerLinksFirstOneOf
	err = newStrictDecoder(data).Decode(&dst.GetManyGroupServiceAccount200ResponseDataInnerLinksFirstOneOf)
	if err == nil {
		jsonGetManyGroupServiceAccount200ResponseDataInnerLinksFirstOneOf, _ := json.Marshal(dst.GetManyGroupServiceAccount200ResponseDataInnerLinksFirstOneOf)
		if string(jsonGetManyGroupServiceAccount200ResponseDataInnerLinksFirstOneOf) == "{}" { // empty struct
			dst.GetManyGroupServiceAccount200ResponseDataInnerLinksFirstOneOf = nil
		} else {
			match++
		}
	} else {
		dst.GetManyGroupServiceAccount200ResponseDataInnerLinksFirstOneOf = nil
	}

	// try to unmarshal data into String
	err = newStrictDecoder(data).Decode(&dst.String)
	if err == nil {
		jsonString, _ := json.Marshal(dst.String)
		if string(jsonString) == "{}" { // empty struct
			dst.String = nil
		} else {
			match++
		}
	} else {
		dst.String = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.GetManyGroupServiceAccount200ResponseDataInnerLinksFirstOneOf = nil
		dst.String = nil

		return fmt.Errorf("data matches more than one schema in oneOf(GetManyGroupServiceAccount200ResponseDataInnerLinksFirst)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(GetManyGroupServiceAccount200ResponseDataInnerLinksFirst)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src GetManyGroupServiceAccount200ResponseDataInnerLinksFirst) MarshalJSON() ([]byte, error) {
	if src.GetManyGroupServiceAccount200ResponseDataInnerLinksFirstOneOf != nil {
		return json.Marshal(&src.GetManyGroupServiceAccount200ResponseDataInnerLinksFirstOneOf)
	}

	if src.String != nil {
		return json.Marshal(&src.String)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *GetManyGroupServiceAccount200ResponseDataInnerLinksFirst) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.GetManyGroupServiceAccount200ResponseDataInnerLinksFirstOneOf != nil {
		return obj.GetManyGroupServiceAccount200ResponseDataInnerLinksFirstOneOf
	}

	if obj.String != nil {
		return obj.String
	}

	// all schemas are nil
	return nil
}

type NullableGetManyGroupServiceAccount200ResponseDataInnerLinksFirst struct {
	value *GetManyGroupServiceAccount200ResponseDataInnerLinksFirst
	isSet bool
}

func (v NullableGetManyGroupServiceAccount200ResponseDataInnerLinksFirst) Get() *GetManyGroupServiceAccount200ResponseDataInnerLinksFirst {
	return v.value
}

func (v *NullableGetManyGroupServiceAccount200ResponseDataInnerLinksFirst) Set(val *GetManyGroupServiceAccount200ResponseDataInnerLinksFirst) {
	v.value = val
	v.isSet = true
}

func (v NullableGetManyGroupServiceAccount200ResponseDataInnerLinksFirst) IsSet() bool {
	return v.isSet
}

func (v *NullableGetManyGroupServiceAccount200ResponseDataInnerLinksFirst) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetManyGroupServiceAccount200ResponseDataInnerLinksFirst(val *GetManyGroupServiceAccount200ResponseDataInnerLinksFirst) *NullableGetManyGroupServiceAccount200ResponseDataInnerLinksFirst {
	return &NullableGetManyGroupServiceAccount200ResponseDataInnerLinksFirst{value: val, isSet: true}
}

func (v NullableGetManyGroupServiceAccount200ResponseDataInnerLinksFirst) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetManyGroupServiceAccount200ResponseDataInnerLinksFirst) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


