/*
Snyk API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: REST
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PatchProjectRequestDataRelationshipsOwner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PatchProjectRequestDataRelationshipsOwner{}

// PatchProjectRequestDataRelationshipsOwner struct for PatchProjectRequestDataRelationshipsOwner
type PatchProjectRequestDataRelationshipsOwner struct {
	Data PatchProjectRequestDataRelationshipsOwnerData `json:"data"`
}

type _PatchProjectRequestDataRelationshipsOwner PatchProjectRequestDataRelationshipsOwner

// NewPatchProjectRequestDataRelationshipsOwner instantiates a new PatchProjectRequestDataRelationshipsOwner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPatchProjectRequestDataRelationshipsOwner(data PatchProjectRequestDataRelationshipsOwnerData) *PatchProjectRequestDataRelationshipsOwner {
	this := PatchProjectRequestDataRelationshipsOwner{}
	this.Data = data
	return &this
}

// NewPatchProjectRequestDataRelationshipsOwnerWithDefaults instantiates a new PatchProjectRequestDataRelationshipsOwner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPatchProjectRequestDataRelationshipsOwnerWithDefaults() *PatchProjectRequestDataRelationshipsOwner {
	this := PatchProjectRequestDataRelationshipsOwner{}
	return &this
}

// GetData returns the Data field value
func (o *PatchProjectRequestDataRelationshipsOwner) GetData() PatchProjectRequestDataRelationshipsOwnerData {
	if o == nil {
		var ret PatchProjectRequestDataRelationshipsOwnerData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *PatchProjectRequestDataRelationshipsOwner) GetDataOk() (*PatchProjectRequestDataRelationshipsOwnerData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *PatchProjectRequestDataRelationshipsOwner) SetData(v PatchProjectRequestDataRelationshipsOwnerData) {
	o.Data = v
}

func (o PatchProjectRequestDataRelationshipsOwner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PatchProjectRequestDataRelationshipsOwner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *PatchProjectRequestDataRelationshipsOwner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPatchProjectRequestDataRelationshipsOwner := _PatchProjectRequestDataRelationshipsOwner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPatchProjectRequestDataRelationshipsOwner)

	if err != nil {
		return err
	}

	*o = PatchProjectRequestDataRelationshipsOwner(varPatchProjectRequestDataRelationshipsOwner)

	return err
}

type NullablePatchProjectRequestDataRelationshipsOwner struct {
	value *PatchProjectRequestDataRelationshipsOwner
	isSet bool
}

func (v NullablePatchProjectRequestDataRelationshipsOwner) Get() *PatchProjectRequestDataRelationshipsOwner {
	return v.value
}

func (v *NullablePatchProjectRequestDataRelationshipsOwner) Set(val *PatchProjectRequestDataRelationshipsOwner) {
	v.value = val
	v.isSet = true
}

func (v NullablePatchProjectRequestDataRelationshipsOwner) IsSet() bool {
	return v.isSet
}

func (v *NullablePatchProjectRequestDataRelationshipsOwner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePatchProjectRequestDataRelationshipsOwner(val *PatchProjectRequestDataRelationshipsOwner) *NullablePatchProjectRequestDataRelationshipsOwner {
	return &NullablePatchProjectRequestDataRelationshipsOwner{value: val, isSet: true}
}

func (v NullablePatchProjectRequestDataRelationshipsOwner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePatchProjectRequestDataRelationshipsOwner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


