/*
Snyk API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: REST
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the OrgUpdateAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OrgUpdateAttributes{}

// OrgUpdateAttributes struct for OrgUpdateAttributes
type OrgUpdateAttributes struct {
	// The display name of the organization.
	Name string `json:"name"`
}

type _OrgUpdateAttributes OrgUpdateAttributes

// NewOrgUpdateAttributes instantiates a new OrgUpdateAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrgUpdateAttributes(name string) *OrgUpdateAttributes {
	this := OrgUpdateAttributes{}
	this.Name = name
	return &this
}

// NewOrgUpdateAttributesWithDefaults instantiates a new OrgUpdateAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrgUpdateAttributesWithDefaults() *OrgUpdateAttributes {
	this := OrgUpdateAttributes{}
	return &this
}

// GetName returns the Name field value
func (o *OrgUpdateAttributes) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *OrgUpdateAttributes) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *OrgUpdateAttributes) SetName(v string) {
	o.Name = v
}

func (o OrgUpdateAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OrgUpdateAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	return toSerialize, nil
}

func (o *OrgUpdateAttributes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOrgUpdateAttributes := _OrgUpdateAttributes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOrgUpdateAttributes)

	if err != nil {
		return err
	}

	*o = OrgUpdateAttributes(varOrgUpdateAttributes)

	return err
}

type NullableOrgUpdateAttributes struct {
	value *OrgUpdateAttributes
	isSet bool
}

func (v NullableOrgUpdateAttributes) Get() *OrgUpdateAttributes {
	return v.value
}

func (v *NullableOrgUpdateAttributes) Set(val *OrgUpdateAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableOrgUpdateAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableOrgUpdateAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrgUpdateAttributes(val *OrgUpdateAttributes) *NullableOrgUpdateAttributes {
	return &NullableOrgUpdateAttributes{value: val, isSet: true}
}

func (v NullableOrgUpdateAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrgUpdateAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


