/*
Snyk API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: REST
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the YarnBuildArgs type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &YarnBuildArgs{}

// YarnBuildArgs struct for YarnBuildArgs
type YarnBuildArgs struct {
	RootWorkspace string `json:"root_workspace"`
}

type _YarnBuildArgs YarnBuildArgs

// NewYarnBuildArgs instantiates a new YarnBuildArgs object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewYarnBuildArgs(rootWorkspace string) *YarnBuildArgs {
	this := YarnBuildArgs{}
	this.RootWorkspace = rootWorkspace
	return &this
}

// NewYarnBuildArgsWithDefaults instantiates a new YarnBuildArgs object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewYarnBuildArgsWithDefaults() *YarnBuildArgs {
	this := YarnBuildArgs{}
	return &this
}

// GetRootWorkspace returns the RootWorkspace field value
func (o *YarnBuildArgs) GetRootWorkspace() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RootWorkspace
}

// GetRootWorkspaceOk returns a tuple with the RootWorkspace field value
// and a boolean to check if the value has been set.
func (o *YarnBuildArgs) GetRootWorkspaceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RootWorkspace, true
}

// SetRootWorkspace sets field value
func (o *YarnBuildArgs) SetRootWorkspace(v string) {
	o.RootWorkspace = v
}

func (o YarnBuildArgs) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o YarnBuildArgs) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["root_workspace"] = o.RootWorkspace
	return toSerialize, nil
}

func (o *YarnBuildArgs) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"root_workspace",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varYarnBuildArgs := _YarnBuildArgs{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varYarnBuildArgs)

	if err != nil {
		return err
	}

	*o = YarnBuildArgs(varYarnBuildArgs)

	return err
}

type NullableYarnBuildArgs struct {
	value *YarnBuildArgs
	isSet bool
}

func (v NullableYarnBuildArgs) Get() *YarnBuildArgs {
	return v.value
}

func (v *NullableYarnBuildArgs) Set(val *YarnBuildArgs) {
	v.value = val
	v.isSet = true
}

func (v NullableYarnBuildArgs) IsSet() bool {
	return v.isSet
}

func (v *NullableYarnBuildArgs) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableYarnBuildArgs(val *YarnBuildArgs) *NullableYarnBuildArgs {
	return &NullableYarnBuildArgs{value: val, isSet: true}
}

func (v NullableYarnBuildArgs) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableYarnBuildArgs) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


