/*
Snyk API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: REST
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PublicAppDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PublicAppDataAttributes{}

// PublicAppDataAttributes struct for PublicAppDataAttributes
type PublicAppDataAttributes struct {
	ClientId string `json:"client_id"`
	// Allow installing the app to a org/group or to a user, default tenant.
	Context *string `json:"context,omitempty"`
	// New name of the app to display to users during authorization flow.
	Name string `json:"name"`
	// The scopes this app is allowed to request during authorization.
	Scopes []string `json:"scopes,omitempty"`
}

type _PublicAppDataAttributes PublicAppDataAttributes

// NewPublicAppDataAttributes instantiates a new PublicAppDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPublicAppDataAttributes(clientId string, name string) *PublicAppDataAttributes {
	this := PublicAppDataAttributes{}
	this.ClientId = clientId
	this.Name = name
	return &this
}

// NewPublicAppDataAttributesWithDefaults instantiates a new PublicAppDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPublicAppDataAttributesWithDefaults() *PublicAppDataAttributes {
	this := PublicAppDataAttributes{}
	return &this
}

// GetClientId returns the ClientId field value
func (o *PublicAppDataAttributes) GetClientId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ClientId
}

// GetClientIdOk returns a tuple with the ClientId field value
// and a boolean to check if the value has been set.
func (o *PublicAppDataAttributes) GetClientIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ClientId, true
}

// SetClientId sets field value
func (o *PublicAppDataAttributes) SetClientId(v string) {
	o.ClientId = v
}

// GetContext returns the Context field value if set, zero value otherwise.
func (o *PublicAppDataAttributes) GetContext() string {
	if o == nil || IsNil(o.Context) {
		var ret string
		return ret
	}
	return *o.Context
}

// GetContextOk returns a tuple with the Context field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PublicAppDataAttributes) GetContextOk() (*string, bool) {
	if o == nil || IsNil(o.Context) {
		return nil, false
	}
	return o.Context, true
}

// HasContext returns a boolean if a field has been set.
func (o *PublicAppDataAttributes) HasContext() bool {
	if o != nil && !IsNil(o.Context) {
		return true
	}

	return false
}

// SetContext gets a reference to the given string and assigns it to the Context field.
func (o *PublicAppDataAttributes) SetContext(v string) {
	o.Context = &v
}

// GetName returns the Name field value
func (o *PublicAppDataAttributes) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *PublicAppDataAttributes) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *PublicAppDataAttributes) SetName(v string) {
	o.Name = v
}

// GetScopes returns the Scopes field value if set, zero value otherwise.
func (o *PublicAppDataAttributes) GetScopes() []string {
	if o == nil || IsNil(o.Scopes) {
		var ret []string
		return ret
	}
	return o.Scopes
}

// GetScopesOk returns a tuple with the Scopes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PublicAppDataAttributes) GetScopesOk() ([]string, bool) {
	if o == nil || IsNil(o.Scopes) {
		return nil, false
	}
	return o.Scopes, true
}

// HasScopes returns a boolean if a field has been set.
func (o *PublicAppDataAttributes) HasScopes() bool {
	if o != nil && !IsNil(o.Scopes) {
		return true
	}

	return false
}

// SetScopes gets a reference to the given []string and assigns it to the Scopes field.
func (o *PublicAppDataAttributes) SetScopes(v []string) {
	o.Scopes = v
}

func (o PublicAppDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PublicAppDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["client_id"] = o.ClientId
	if !IsNil(o.Context) {
		toSerialize["context"] = o.Context
	}
	toSerialize["name"] = o.Name
	if !IsNil(o.Scopes) {
		toSerialize["scopes"] = o.Scopes
	}
	return toSerialize, nil
}

func (o *PublicAppDataAttributes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"client_id",
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPublicAppDataAttributes := _PublicAppDataAttributes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPublicAppDataAttributes)

	if err != nil {
		return err
	}

	*o = PublicAppDataAttributes(varPublicAppDataAttributes)

	return err
}

type NullablePublicAppDataAttributes struct {
	value *PublicAppDataAttributes
	isSet bool
}

func (v NullablePublicAppDataAttributes) Get() *PublicAppDataAttributes {
	return v.value
}

func (v *NullablePublicAppDataAttributes) Set(val *PublicAppDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullablePublicAppDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullablePublicAppDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePublicAppDataAttributes(val *PublicAppDataAttributes) *NullablePublicAppDataAttributes {
	return &NullablePublicAppDataAttributes{value: val, isSet: true}
}

func (v NullablePublicAppDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePublicAppDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


