/*
Snyk API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: REST
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GetManyGroupServiceAccount200ResponseDataInnerLinksFirstOneOf type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetManyGroupServiceAccount200ResponseDataInnerLinksFirstOneOf{}

// GetManyGroupServiceAccount200ResponseDataInnerLinksFirstOneOf struct for GetManyGroupServiceAccount200ResponseDataInnerLinksFirstOneOf
type GetManyGroupServiceAccount200ResponseDataInnerLinksFirstOneOf struct {
	// A string containing the link’s URL.
	Href string `json:"href"`
	// Free-form object that may contain non-standard information.
	Meta map[string]interface{} `json:"meta,omitempty"`
}

type _GetManyGroupServiceAccount200ResponseDataInnerLinksFirstOneOf GetManyGroupServiceAccount200ResponseDataInnerLinksFirstOneOf

// NewGetManyGroupServiceAccount200ResponseDataInnerLinksFirstOneOf instantiates a new GetManyGroupServiceAccount200ResponseDataInnerLinksFirstOneOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetManyGroupServiceAccount200ResponseDataInnerLinksFirstOneOf(href string) *GetManyGroupServiceAccount200ResponseDataInnerLinksFirstOneOf {
	this := GetManyGroupServiceAccount200ResponseDataInnerLinksFirstOneOf{}
	this.Href = href
	return &this
}

// NewGetManyGroupServiceAccount200ResponseDataInnerLinksFirstOneOfWithDefaults instantiates a new GetManyGroupServiceAccount200ResponseDataInnerLinksFirstOneOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetManyGroupServiceAccount200ResponseDataInnerLinksFirstOneOfWithDefaults() *GetManyGroupServiceAccount200ResponseDataInnerLinksFirstOneOf {
	this := GetManyGroupServiceAccount200ResponseDataInnerLinksFirstOneOf{}
	return &this
}

// GetHref returns the Href field value
func (o *GetManyGroupServiceAccount200ResponseDataInnerLinksFirstOneOf) GetHref() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Href
}

// GetHrefOk returns a tuple with the Href field value
// and a boolean to check if the value has been set.
func (o *GetManyGroupServiceAccount200ResponseDataInnerLinksFirstOneOf) GetHrefOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Href, true
}

// SetHref sets field value
func (o *GetManyGroupServiceAccount200ResponseDataInnerLinksFirstOneOf) SetHref(v string) {
	o.Href = v
}

// GetMeta returns the Meta field value if set, zero value otherwise.
func (o *GetManyGroupServiceAccount200ResponseDataInnerLinksFirstOneOf) GetMeta() map[string]interface{} {
	if o == nil || IsNil(o.Meta) {
		var ret map[string]interface{}
		return ret
	}
	return o.Meta
}

// GetMetaOk returns a tuple with the Meta field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetManyGroupServiceAccount200ResponseDataInnerLinksFirstOneOf) GetMetaOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Meta) {
		return map[string]interface{}{}, false
	}
	return o.Meta, true
}

// HasMeta returns a boolean if a field has been set.
func (o *GetManyGroupServiceAccount200ResponseDataInnerLinksFirstOneOf) HasMeta() bool {
	if o != nil && !IsNil(o.Meta) {
		return true
	}

	return false
}

// SetMeta gets a reference to the given map[string]interface{} and assigns it to the Meta field.
func (o *GetManyGroupServiceAccount200ResponseDataInnerLinksFirstOneOf) SetMeta(v map[string]interface{}) {
	o.Meta = v
}

func (o GetManyGroupServiceAccount200ResponseDataInnerLinksFirstOneOf) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetManyGroupServiceAccount200ResponseDataInnerLinksFirstOneOf) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["href"] = o.Href
	if !IsNil(o.Meta) {
		toSerialize["meta"] = o.Meta
	}
	return toSerialize, nil
}

func (o *GetManyGroupServiceAccount200ResponseDataInnerLinksFirstOneOf) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"href",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetManyGroupServiceAccount200ResponseDataInnerLinksFirstOneOf := _GetManyGroupServiceAccount200ResponseDataInnerLinksFirstOneOf{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetManyGroupServiceAccount200ResponseDataInnerLinksFirstOneOf)

	if err != nil {
		return err
	}

	*o = GetManyGroupServiceAccount200ResponseDataInnerLinksFirstOneOf(varGetManyGroupServiceAccount200ResponseDataInnerLinksFirstOneOf)

	return err
}

type NullableGetManyGroupServiceAccount200ResponseDataInnerLinksFirstOneOf struct {
	value *GetManyGroupServiceAccount200ResponseDataInnerLinksFirstOneOf
	isSet bool
}

func (v NullableGetManyGroupServiceAccount200ResponseDataInnerLinksFirstOneOf) Get() *GetManyGroupServiceAccount200ResponseDataInnerLinksFirstOneOf {
	return v.value
}

func (v *NullableGetManyGroupServiceAccount200ResponseDataInnerLinksFirstOneOf) Set(val *GetManyGroupServiceAccount200ResponseDataInnerLinksFirstOneOf) {
	v.value = val
	v.isSet = true
}

func (v NullableGetManyGroupServiceAccount200ResponseDataInnerLinksFirstOneOf) IsSet() bool {
	return v.isSet
}

func (v *NullableGetManyGroupServiceAccount200ResponseDataInnerLinksFirstOneOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetManyGroupServiceAccount200ResponseDataInnerLinksFirstOneOf(val *GetManyGroupServiceAccount200ResponseDataInnerLinksFirstOneOf) *NullableGetManyGroupServiceAccount200ResponseDataInnerLinksFirstOneOf {
	return &NullableGetManyGroupServiceAccount200ResponseDataInnerLinksFirstOneOf{value: val, isSet: true}
}

func (v NullableGetManyGroupServiceAccount200ResponseDataInnerLinksFirstOneOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetManyGroupServiceAccount200ResponseDataInnerLinksFirstOneOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


