/*
Snyk API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: REST
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SbomResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SbomResponse{}

// SbomResponse struct for SbomResponse
type SbomResponse struct {
	Data SbomResource `json:"data"`
	Jsonapi JsonApi `json:"jsonapi"`
}

type _SbomResponse SbomResponse

// NewSbomResponse instantiates a new SbomResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSbomResponse(data SbomResource, jsonapi JsonApi) *SbomResponse {
	this := SbomResponse{}
	this.Data = data
	this.Jsonapi = jsonapi
	return &this
}

// NewSbomResponseWithDefaults instantiates a new SbomResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSbomResponseWithDefaults() *SbomResponse {
	this := SbomResponse{}
	return &this
}

// GetData returns the Data field value
func (o *SbomResponse) GetData() SbomResource {
	if o == nil {
		var ret SbomResource
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *SbomResponse) GetDataOk() (*SbomResource, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *SbomResponse) SetData(v SbomResource) {
	o.Data = v
}

// GetJsonapi returns the Jsonapi field value
func (o *SbomResponse) GetJsonapi() JsonApi {
	if o == nil {
		var ret JsonApi
		return ret
	}

	return o.Jsonapi
}

// GetJsonapiOk returns a tuple with the Jsonapi field value
// and a boolean to check if the value has been set.
func (o *SbomResponse) GetJsonapiOk() (*JsonApi, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Jsonapi, true
}

// SetJsonapi sets field value
func (o *SbomResponse) SetJsonapi(v JsonApi) {
	o.Jsonapi = v
}

func (o SbomResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SbomResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	toSerialize["jsonapi"] = o.Jsonapi
	return toSerialize, nil
}

func (o *SbomResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
		"jsonapi",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSbomResponse := _SbomResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSbomResponse)

	if err != nil {
		return err
	}

	*o = SbomResponse(varSbomResponse)

	return err
}

type NullableSbomResponse struct {
	value *SbomResponse
	isSet bool
}

func (v NullableSbomResponse) Get() *SbomResponse {
	return v.value
}

func (v *NullableSbomResponse) Set(val *SbomResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableSbomResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableSbomResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSbomResponse(val *SbomResponse) *NullableSbomResponse {
	return &NullableSbomResponse{value: val, isSet: true}
}

func (v NullableSbomResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSbomResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


