/*
Snyk API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: REST
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ProjectSettingsPatchRequestData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProjectSettingsPatchRequestData{}

// ProjectSettingsPatchRequestData struct for ProjectSettingsPatchRequestData
type ProjectSettingsPatchRequestData struct {
	Attributes ProjectSettingsPatchRequestDataAttributes `json:"attributes"`
	Id string `json:"id"`
	Type string `json:"type"`
}

type _ProjectSettingsPatchRequestData ProjectSettingsPatchRequestData

// NewProjectSettingsPatchRequestData instantiates a new ProjectSettingsPatchRequestData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProjectSettingsPatchRequestData(attributes ProjectSettingsPatchRequestDataAttributes, id string, type_ string) *ProjectSettingsPatchRequestData {
	this := ProjectSettingsPatchRequestData{}
	this.Attributes = attributes
	this.Id = id
	this.Type = type_
	return &this
}

// NewProjectSettingsPatchRequestDataWithDefaults instantiates a new ProjectSettingsPatchRequestData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProjectSettingsPatchRequestDataWithDefaults() *ProjectSettingsPatchRequestData {
	this := ProjectSettingsPatchRequestData{}
	return &this
}

// GetAttributes returns the Attributes field value
func (o *ProjectSettingsPatchRequestData) GetAttributes() ProjectSettingsPatchRequestDataAttributes {
	if o == nil {
		var ret ProjectSettingsPatchRequestDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *ProjectSettingsPatchRequestData) GetAttributesOk() (*ProjectSettingsPatchRequestDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *ProjectSettingsPatchRequestData) SetAttributes(v ProjectSettingsPatchRequestDataAttributes) {
	o.Attributes = v
}

// GetId returns the Id field value
func (o *ProjectSettingsPatchRequestData) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ProjectSettingsPatchRequestData) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ProjectSettingsPatchRequestData) SetId(v string) {
	o.Id = v
}

// GetType returns the Type field value
func (o *ProjectSettingsPatchRequestData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *ProjectSettingsPatchRequestData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *ProjectSettingsPatchRequestData) SetType(v string) {
	o.Type = v
}

func (o ProjectSettingsPatchRequestData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProjectSettingsPatchRequestData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["attributes"] = o.Attributes
	toSerialize["id"] = o.Id
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

func (o *ProjectSettingsPatchRequestData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"attributes",
		"id",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varProjectSettingsPatchRequestData := _ProjectSettingsPatchRequestData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varProjectSettingsPatchRequestData)

	if err != nil {
		return err
	}

	*o = ProjectSettingsPatchRequestData(varProjectSettingsPatchRequestData)

	return err
}

type NullableProjectSettingsPatchRequestData struct {
	value *ProjectSettingsPatchRequestData
	isSet bool
}

func (v NullableProjectSettingsPatchRequestData) Get() *ProjectSettingsPatchRequestData {
	return v.value
}

func (v *NullableProjectSettingsPatchRequestData) Set(val *ProjectSettingsPatchRequestData) {
	v.value = val
	v.isSet = true
}

func (v NullableProjectSettingsPatchRequestData) IsSet() bool {
	return v.isSet
}

func (v *NullableProjectSettingsPatchRequestData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProjectSettingsPatchRequestData(val *ProjectSettingsPatchRequestData) *NullableProjectSettingsPatchRequestData {
	return &NullableProjectSettingsPatchRequestData{value: val, isSet: true}
}

func (v NullableProjectSettingsPatchRequestData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProjectSettingsPatchRequestData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


