/*
Snyk API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: REST
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the MemberRoleRelationship type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MemberRoleRelationship{}

// MemberRoleRelationship struct for MemberRoleRelationship
type MemberRoleRelationship struct {
	Data MemberRoleRelationshipData `json:"data"`
}

type _MemberRoleRelationship MemberRoleRelationship

// NewMemberRoleRelationship instantiates a new MemberRoleRelationship object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMemberRoleRelationship(data MemberRoleRelationshipData) *MemberRoleRelationship {
	this := MemberRoleRelationship{}
	this.Data = data
	return &this
}

// NewMemberRoleRelationshipWithDefaults instantiates a new MemberRoleRelationship object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMemberRoleRelationshipWithDefaults() *MemberRoleRelationship {
	this := MemberRoleRelationship{}
	return &this
}

// GetData returns the Data field value
func (o *MemberRoleRelationship) GetData() MemberRoleRelationshipData {
	if o == nil {
		var ret MemberRoleRelationshipData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *MemberRoleRelationship) GetDataOk() (*MemberRoleRelationshipData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *MemberRoleRelationship) SetData(v MemberRoleRelationshipData) {
	o.Data = v
}

func (o MemberRoleRelationship) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MemberRoleRelationship) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *MemberRoleRelationship) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMemberRoleRelationship := _MemberRoleRelationship{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMemberRoleRelationship)

	if err != nil {
		return err
	}

	*o = MemberRoleRelationship(varMemberRoleRelationship)

	return err
}

type NullableMemberRoleRelationship struct {
	value *MemberRoleRelationship
	isSet bool
}

func (v NullableMemberRoleRelationship) Get() *MemberRoleRelationship {
	return v.value
}

func (v *NullableMemberRoleRelationship) Set(val *MemberRoleRelationship) {
	v.value = val
	v.isSet = true
}

func (v NullableMemberRoleRelationship) IsSet() bool {
	return v.isSet
}

func (v *NullableMemberRoleRelationship) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMemberRoleRelationship(val *MemberRoleRelationship) *NullableMemberRoleRelationship {
	return &NullableMemberRoleRelationship{value: val, isSet: true}
}

func (v NullableMemberRoleRelationship) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMemberRoleRelationship) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


