/*
Snyk API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: REST
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GetIacSettingsForGroup200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetIacSettingsForGroup200Response{}

// GetIacSettingsForGroup200Response struct for GetIacSettingsForGroup200Response
type GetIacSettingsForGroup200Response struct {
	Data GroupIacSettingsResponse `json:"data"`
	Jsonapi JsonApi `json:"jsonapi"`
	Links Links `json:"links"`
}

type _GetIacSettingsForGroup200Response GetIacSettingsForGroup200Response

// NewGetIacSettingsForGroup200Response instantiates a new GetIacSettingsForGroup200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetIacSettingsForGroup200Response(data GroupIacSettingsResponse, jsonapi JsonApi, links Links) *GetIacSettingsForGroup200Response {
	this := GetIacSettingsForGroup200Response{}
	this.Data = data
	this.Jsonapi = jsonapi
	this.Links = links
	return &this
}

// NewGetIacSettingsForGroup200ResponseWithDefaults instantiates a new GetIacSettingsForGroup200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetIacSettingsForGroup200ResponseWithDefaults() *GetIacSettingsForGroup200Response {
	this := GetIacSettingsForGroup200Response{}
	return &this
}

// GetData returns the Data field value
func (o *GetIacSettingsForGroup200Response) GetData() GroupIacSettingsResponse {
	if o == nil {
		var ret GroupIacSettingsResponse
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *GetIacSettingsForGroup200Response) GetDataOk() (*GroupIacSettingsResponse, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *GetIacSettingsForGroup200Response) SetData(v GroupIacSettingsResponse) {
	o.Data = v
}

// GetJsonapi returns the Jsonapi field value
func (o *GetIacSettingsForGroup200Response) GetJsonapi() JsonApi {
	if o == nil {
		var ret JsonApi
		return ret
	}

	return o.Jsonapi
}

// GetJsonapiOk returns a tuple with the Jsonapi field value
// and a boolean to check if the value has been set.
func (o *GetIacSettingsForGroup200Response) GetJsonapiOk() (*JsonApi, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Jsonapi, true
}

// SetJsonapi sets field value
func (o *GetIacSettingsForGroup200Response) SetJsonapi(v JsonApi) {
	o.Jsonapi = v
}

// GetLinks returns the Links field value
func (o *GetIacSettingsForGroup200Response) GetLinks() Links {
	if o == nil {
		var ret Links
		return ret
	}

	return o.Links
}

// GetLinksOk returns a tuple with the Links field value
// and a boolean to check if the value has been set.
func (o *GetIacSettingsForGroup200Response) GetLinksOk() (*Links, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Links, true
}

// SetLinks sets field value
func (o *GetIacSettingsForGroup200Response) SetLinks(v Links) {
	o.Links = v
}

func (o GetIacSettingsForGroup200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetIacSettingsForGroup200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	toSerialize["jsonapi"] = o.Jsonapi
	toSerialize["links"] = o.Links
	return toSerialize, nil
}

func (o *GetIacSettingsForGroup200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
		"jsonapi",
		"links",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetIacSettingsForGroup200Response := _GetIacSettingsForGroup200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetIacSettingsForGroup200Response)

	if err != nil {
		return err
	}

	*o = GetIacSettingsForGroup200Response(varGetIacSettingsForGroup200Response)

	return err
}

type NullableGetIacSettingsForGroup200Response struct {
	value *GetIacSettingsForGroup200Response
	isSet bool
}

func (v NullableGetIacSettingsForGroup200Response) Get() *GetIacSettingsForGroup200Response {
	return v.value
}

func (v *NullableGetIacSettingsForGroup200Response) Set(val *GetIacSettingsForGroup200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetIacSettingsForGroup200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetIacSettingsForGroup200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetIacSettingsForGroup200Response(val *GetIacSettingsForGroup200Response) *NullableGetIacSettingsForGroup200Response {
	return &NullableGetIacSettingsForGroup200Response{value: val, isSet: true}
}

func (v NullableGetIacSettingsForGroup200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetIacSettingsForGroup200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


