/*
Snyk API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: REST
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
)

// checks if the OrgIacSettingsResponseAttributesCustomRulesParentsGroup type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OrgIacSettingsResponseAttributesCustomRulesParentsGroup{}

// OrgIacSettingsResponseAttributesCustomRulesParentsGroup The Infrastructure as Code settings at the group level.
type OrgIacSettingsResponseAttributesCustomRulesParentsGroup struct {
	CustomRules *GroupIacSettingsResponseAttributesCustomRules `json:"custom_rules,omitempty"`
	// The last time the settings were updated.
	Updated *time.Time `json:"updated,omitempty"`
}

// NewOrgIacSettingsResponseAttributesCustomRulesParentsGroup instantiates a new OrgIacSettingsResponseAttributesCustomRulesParentsGroup object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrgIacSettingsResponseAttributesCustomRulesParentsGroup() *OrgIacSettingsResponseAttributesCustomRulesParentsGroup {
	this := OrgIacSettingsResponseAttributesCustomRulesParentsGroup{}
	return &this
}

// NewOrgIacSettingsResponseAttributesCustomRulesParentsGroupWithDefaults instantiates a new OrgIacSettingsResponseAttributesCustomRulesParentsGroup object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrgIacSettingsResponseAttributesCustomRulesParentsGroupWithDefaults() *OrgIacSettingsResponseAttributesCustomRulesParentsGroup {
	this := OrgIacSettingsResponseAttributesCustomRulesParentsGroup{}
	return &this
}

// GetCustomRules returns the CustomRules field value if set, zero value otherwise.
func (o *OrgIacSettingsResponseAttributesCustomRulesParentsGroup) GetCustomRules() GroupIacSettingsResponseAttributesCustomRules {
	if o == nil || IsNil(o.CustomRules) {
		var ret GroupIacSettingsResponseAttributesCustomRules
		return ret
	}
	return *o.CustomRules
}

// GetCustomRulesOk returns a tuple with the CustomRules field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrgIacSettingsResponseAttributesCustomRulesParentsGroup) GetCustomRulesOk() (*GroupIacSettingsResponseAttributesCustomRules, bool) {
	if o == nil || IsNil(o.CustomRules) {
		return nil, false
	}
	return o.CustomRules, true
}

// HasCustomRules returns a boolean if a field has been set.
func (o *OrgIacSettingsResponseAttributesCustomRulesParentsGroup) HasCustomRules() bool {
	if o != nil && !IsNil(o.CustomRules) {
		return true
	}

	return false
}

// SetCustomRules gets a reference to the given GroupIacSettingsResponseAttributesCustomRules and assigns it to the CustomRules field.
func (o *OrgIacSettingsResponseAttributesCustomRulesParentsGroup) SetCustomRules(v GroupIacSettingsResponseAttributesCustomRules) {
	o.CustomRules = &v
}

// GetUpdated returns the Updated field value if set, zero value otherwise.
func (o *OrgIacSettingsResponseAttributesCustomRulesParentsGroup) GetUpdated() time.Time {
	if o == nil || IsNil(o.Updated) {
		var ret time.Time
		return ret
	}
	return *o.Updated
}

// GetUpdatedOk returns a tuple with the Updated field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrgIacSettingsResponseAttributesCustomRulesParentsGroup) GetUpdatedOk() (*time.Time, bool) {
	if o == nil || IsNil(o.Updated) {
		return nil, false
	}
	return o.Updated, true
}

// HasUpdated returns a boolean if a field has been set.
func (o *OrgIacSettingsResponseAttributesCustomRulesParentsGroup) HasUpdated() bool {
	if o != nil && !IsNil(o.Updated) {
		return true
	}

	return false
}

// SetUpdated gets a reference to the given time.Time and assigns it to the Updated field.
func (o *OrgIacSettingsResponseAttributesCustomRulesParentsGroup) SetUpdated(v time.Time) {
	o.Updated = &v
}

func (o OrgIacSettingsResponseAttributesCustomRulesParentsGroup) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OrgIacSettingsResponseAttributesCustomRulesParentsGroup) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CustomRules) {
		toSerialize["custom_rules"] = o.CustomRules
	}
	if !IsNil(o.Updated) {
		toSerialize["updated"] = o.Updated
	}
	return toSerialize, nil
}

type NullableOrgIacSettingsResponseAttributesCustomRulesParentsGroup struct {
	value *OrgIacSettingsResponseAttributesCustomRulesParentsGroup
	isSet bool
}

func (v NullableOrgIacSettingsResponseAttributesCustomRulesParentsGroup) Get() *OrgIacSettingsResponseAttributesCustomRulesParentsGroup {
	return v.value
}

func (v *NullableOrgIacSettingsResponseAttributesCustomRulesParentsGroup) Set(val *OrgIacSettingsResponseAttributesCustomRulesParentsGroup) {
	v.value = val
	v.isSet = true
}

func (v NullableOrgIacSettingsResponseAttributesCustomRulesParentsGroup) IsSet() bool {
	return v.isSet
}

func (v *NullableOrgIacSettingsResponseAttributesCustomRulesParentsGroup) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrgIacSettingsResponseAttributesCustomRulesParentsGroup(val *OrgIacSettingsResponseAttributesCustomRulesParentsGroup) *NullableOrgIacSettingsResponseAttributesCustomRulesParentsGroup {
	return &NullableOrgIacSettingsResponseAttributesCustomRulesParentsGroup{value: val, isSet: true}
}

func (v NullableOrgIacSettingsResponseAttributesCustomRulesParentsGroup) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrgIacSettingsResponseAttributesCustomRulesParentsGroup) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


