/*
Snyk API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: REST
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UpdateGroupServiceAccountRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateGroupServiceAccountRequest{}

// UpdateGroupServiceAccountRequest struct for UpdateGroupServiceAccountRequest
type UpdateGroupServiceAccountRequest struct {
	Data UpdateGroupServiceAccountRequestData `json:"data"`
}

type _UpdateGroupServiceAccountRequest UpdateGroupServiceAccountRequest

// NewUpdateGroupServiceAccountRequest instantiates a new UpdateGroupServiceAccountRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateGroupServiceAccountRequest(data UpdateGroupServiceAccountRequestData) *UpdateGroupServiceAccountRequest {
	this := UpdateGroupServiceAccountRequest{}
	this.Data = data
	return &this
}

// NewUpdateGroupServiceAccountRequestWithDefaults instantiates a new UpdateGroupServiceAccountRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateGroupServiceAccountRequestWithDefaults() *UpdateGroupServiceAccountRequest {
	this := UpdateGroupServiceAccountRequest{}
	return &this
}

// GetData returns the Data field value
func (o *UpdateGroupServiceAccountRequest) GetData() UpdateGroupServiceAccountRequestData {
	if o == nil {
		var ret UpdateGroupServiceAccountRequestData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *UpdateGroupServiceAccountRequest) GetDataOk() (*UpdateGroupServiceAccountRequestData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *UpdateGroupServiceAccountRequest) SetData(v UpdateGroupServiceAccountRequestData) {
	o.Data = v
}

func (o UpdateGroupServiceAccountRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateGroupServiceAccountRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *UpdateGroupServiceAccountRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateGroupServiceAccountRequest := _UpdateGroupServiceAccountRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateGroupServiceAccountRequest)

	if err != nil {
		return err
	}

	*o = UpdateGroupServiceAccountRequest(varUpdateGroupServiceAccountRequest)

	return err
}

type NullableUpdateGroupServiceAccountRequest struct {
	value *UpdateGroupServiceAccountRequest
	isSet bool
}

func (v NullableUpdateGroupServiceAccountRequest) Get() *UpdateGroupServiceAccountRequest {
	return v.value
}

func (v *NullableUpdateGroupServiceAccountRequest) Set(val *UpdateGroupServiceAccountRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateGroupServiceAccountRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateGroupServiceAccountRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateGroupServiceAccountRequest(val *UpdateGroupServiceAccountRequest) *NullableUpdateGroupServiceAccountRequest {
	return &NullableUpdateGroupServiceAccountRequest{value: val, isSet: true}
}

func (v NullableUpdateGroupServiceAccountRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateGroupServiceAccountRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


