/*
Snyk API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: REST
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GetUserInstalledApps200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetUserInstalledApps200Response{}

// GetUserInstalledApps200Response struct for GetUserInstalledApps200Response
type GetUserInstalledApps200Response struct {
	Data []PublicApp `json:"data"`
	Jsonapi JsonApi `json:"jsonapi"`
	Links PaginatedLinks `json:"links"`
}

type _GetUserInstalledApps200Response GetUserInstalledApps200Response

// NewGetUserInstalledApps200Response instantiates a new GetUserInstalledApps200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetUserInstalledApps200Response(data []PublicApp, jsonapi JsonApi, links PaginatedLinks) *GetUserInstalledApps200Response {
	this := GetUserInstalledApps200Response{}
	this.Data = data
	this.Jsonapi = jsonapi
	this.Links = links
	return &this
}

// NewGetUserInstalledApps200ResponseWithDefaults instantiates a new GetUserInstalledApps200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetUserInstalledApps200ResponseWithDefaults() *GetUserInstalledApps200Response {
	this := GetUserInstalledApps200Response{}
	return &this
}

// GetData returns the Data field value
func (o *GetUserInstalledApps200Response) GetData() []PublicApp {
	if o == nil {
		var ret []PublicApp
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *GetUserInstalledApps200Response) GetDataOk() ([]PublicApp, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *GetUserInstalledApps200Response) SetData(v []PublicApp) {
	o.Data = v
}

// GetJsonapi returns the Jsonapi field value
func (o *GetUserInstalledApps200Response) GetJsonapi() JsonApi {
	if o == nil {
		var ret JsonApi
		return ret
	}

	return o.Jsonapi
}

// GetJsonapiOk returns a tuple with the Jsonapi field value
// and a boolean to check if the value has been set.
func (o *GetUserInstalledApps200Response) GetJsonapiOk() (*JsonApi, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Jsonapi, true
}

// SetJsonapi sets field value
func (o *GetUserInstalledApps200Response) SetJsonapi(v JsonApi) {
	o.Jsonapi = v
}

// GetLinks returns the Links field value
func (o *GetUserInstalledApps200Response) GetLinks() PaginatedLinks {
	if o == nil {
		var ret PaginatedLinks
		return ret
	}

	return o.Links
}

// GetLinksOk returns a tuple with the Links field value
// and a boolean to check if the value has been set.
func (o *GetUserInstalledApps200Response) GetLinksOk() (*PaginatedLinks, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Links, true
}

// SetLinks sets field value
func (o *GetUserInstalledApps200Response) SetLinks(v PaginatedLinks) {
	o.Links = v
}

func (o GetUserInstalledApps200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetUserInstalledApps200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	toSerialize["jsonapi"] = o.Jsonapi
	toSerialize["links"] = o.Links
	return toSerialize, nil
}

func (o *GetUserInstalledApps200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
		"jsonapi",
		"links",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetUserInstalledApps200Response := _GetUserInstalledApps200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetUserInstalledApps200Response)

	if err != nil {
		return err
	}

	*o = GetUserInstalledApps200Response(varGetUserInstalledApps200Response)

	return err
}

type NullableGetUserInstalledApps200Response struct {
	value *GetUserInstalledApps200Response
	isSet bool
}

func (v NullableGetUserInstalledApps200Response) Get() *GetUserInstalledApps200Response {
	return v.value
}

func (v *NullableGetUserInstalledApps200Response) Set(val *GetUserInstalledApps200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetUserInstalledApps200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetUserInstalledApps200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetUserInstalledApps200Response(val *GetUserInstalledApps200Response) *NullableGetUserInstalledApps200Response {
	return &NullableGetUserInstalledApps200Response{value: val, isSet: true}
}

func (v NullableGetUserInstalledApps200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetUserInstalledApps200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


