/*
Snyk API

Testing ContainerImageAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_openapi_ContainerImageAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test ContainerImageAPIService GetContainerImage", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var orgId string
		var imageId string

		resp, httpRes, err := apiClient.ContainerImageAPI.GetContainerImage(context.Background(), orgId, imageId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ContainerImageAPIService ListContainerImage", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var orgId string

		resp, httpRes, err := apiClient.ContainerImageAPI.ListContainerImage(context.Background(), orgId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ContainerImageAPIService ListImageTargetRefs", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var orgId string
		var imageId string

		resp, httpRes, err := apiClient.ContainerImageAPI.ListImageTargetRefs(context.Background(), orgId, imageId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
